/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\pure\os.o nimcache\lib\pure\os.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

#include <errno.h>
typedef struct TY3985 TY3985;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TY8802 TY8802;
typedef struct TY8818 TY8818;
typedef struct TY9190 TY9190;
typedef struct TY8814 TY8814;
typedef struct TY8810 TY8810;
typedef struct TY9188 TY9188;
typedef struct TY117115 TY117115;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY8802 {
NI Refcount;
TNimType* Typ;
};
struct TY8818 {
NI Len;
NI Cap;
TY8802** D;
};
struct TY8814 {
NI Counter;
NI Max;
TY8810* Head;
TY8810** Data;
};
struct TY9188 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
};
struct TY9190 {
TY8818 Zct;
TY8818 Decstack;
TY8814 Cycleroots;
TY8818 Tempstack;
TY9188 Stat;
};
struct TY117115 {
NimStringDesc* Dir;
NimStringDesc* Name;
NimStringDesc* Ext;
};
typedef NI TY7014[16];
struct TY8810 {
TY8810* Next;
NI Key;
TY7014 Bits;
};
struct TY3985 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, newSeq)(TNimType* Typ_9221, NI Len_9222);
static N_INLINE(void, asgnRefNoCycle)(void** Dest_10019, void* Src_10020);
static N_INLINE(TY8802*, Usrtocell_9234)(void* Usr_9236);
N_NOINLINE(void, Addzct_9223)(TY8818* S_9226, TY8802* C_9227);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* Src_14308);
static N_INLINE(NI, subInt)(NI A_5403, NI B_5404);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI Space_14287);
static N_INLINE(void, appendString)(NimStringDesc* Dest_14392, NimStringDesc* Src_14393);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* S_1544, NI First_1545);
static N_INLINE(void, appendChar)(NimStringDesc* Dest_14409, NIM_CHAR C_14410);
N_NIMCALL(void, unsureAsgnRef)(void** Dest_9213, void* Src_9214);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* S_1548, NI First_1549, NI Last_1550);
static N_INLINE(NI, addInt)(NI A_5203, NI B_5204);
STRING_LITERAL(TMP124168, "", 0);
NIM_BOOL Envcomputed_117820;
TY3985* Environment_117838;
extern TNimType* NTI3985; /* seq[string] */
extern TY9190 Gch_9208;
TY3985* Ownargv_119802;
static N_INLINE(TY8802*, Usrtocell_9234)(void* Usr_9236) {
TY8802* Result_9237;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "system.usrToCell";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\system\\gc.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_9237 = 0;
F.line = 96;
Result_9237 = ((TY8802*) ((NI32)((NU32)(((NI) (Usr_9236))) - (NU32)(((NI) (((NI)sizeof(TY8802))))))));
framePtr = framePtr->prev;
return Result_9237;
}
static N_INLINE(void, asgnRefNoCycle)(void** Dest_10019, void* Src_10020) {
TY8802* C_10021;
TY8802* C_10022;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "system.asgnRefNoCycle";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\system\\gc.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
F.line = 253;
if (!!((Src_10020 == 0))) goto LA3;
C_10021 = 0;
F.line = 254;
C_10021 = Usrtocell_9234(Src_10020);
F.line = 255;
(*C_10021).Refcount = (NI32)((NU32)((*C_10021).Refcount) + (NU32)(8));
LA3: ;
F.line = 256;
if (!!(((*Dest_10019) == 0))) goto LA9;
C_10022 = 0;
F.line = 257;
C_10022 = Usrtocell_9234((*Dest_10019));
F.line = 258;
(*C_10022).Refcount = (NI32)((NU32)((*C_10022).Refcount) - (NU32)(8));
F.line = 259;
if (!((NU32)((*C_10022).Refcount) < (NU32)(8))) goto LA15;
F.line = 260;
Addzct_9223(&Gch_9208.Zct, C_10022);
LA15: ;
LA9: ;
F.line = 261;
(*Dest_10019) = Src_10020;
framePtr = framePtr->prev;
}
static N_INLINE(NI, subInt)(NI A_5403, NI B_5404) {
NI Result_5405;
NIM_BOOL LOC2;
Result_5405 = 0;
Result_5405 = (NI32)((NU32)(A_5403) - (NU32)(B_5404));
LOC2 = (0 <= (NI32)(Result_5405 ^ A_5403));
if (LOC2) goto LA3;
LOC2 = (0 <= (NI32)(Result_5405 ^ (NI32)((NU32) ~(B_5404))));
LA3: ;
if (!LOC2) goto LA4;
goto BeforeRet;
LA4: ;
raiseOverflow();
BeforeRet: ;
return Result_5405;
}
static N_INLINE(void, appendString)(NimStringDesc* Dest_14392, NimStringDesc* Src_14393) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "system.appendString";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\system\\sysstr.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
F.line = 149;
memcpy(((NCSTRING) (&(*Dest_14392).data[((*Dest_14392).Sup.len)-0])), ((NCSTRING) ((*Src_14393).data)), ((NI32) ((NI32)((NI32)((*Src_14393).Sup.len + 1) * 1))));
F.line = 150;
(*Dest_14392).Sup.len += (*Src_14393).Sup.len;
framePtr = framePtr->prev;
}
static N_INLINE(void, appendChar)(NimStringDesc* Dest_14409, NIM_CHAR C_14410) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "system.appendChar";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\system\\sysstr.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
F.line = 153;
(*Dest_14409).data[((*Dest_14409).Sup.len)-0] = C_14410;
F.line = 154;
(*Dest_14409).data[((NI32)((*Dest_14409).Sup.len + 1))-0] = 0;
F.line = 155;
(*Dest_14409).Sup.len += 1;
framePtr = framePtr->prev;
}
N_NIMCALL(NimStringDesc*, Joinpath_116801)(NimStringDesc* Head_116803, NimStringDesc* Tail_116804) {
NimStringDesc* Result_116805;
NimStringDesc* LOC13;
NimStringDesc* LOC14;
NimStringDesc* LOC16;
NimStringDesc* LOC22;
NimStringDesc* LOC24;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "os.JoinPath";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\os.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_116805 = 0;
F.line = 332;
if (!(Head_116803->Sup.len == 0)) goto LA3;
F.line = 333;
Result_116805 = copyString(Tail_116804);
goto LA2;
LA3: ;
if ((NU)(subInt(Head_116803->Sup.len, 1)) > (NU)(Head_116803->Sup.len)) raiseIndexError();
if (!(((NU8)(Head_116803->data[subInt(Head_116803->Sup.len, 1)])) == ((NU8)(92)) || ((NU8)(Head_116803->data[subInt(Head_116803->Sup.len, 1)])) == ((NU8)(47)))) goto LA6;
F.line = 335;
if ((NU)(0) > (NU)(Tail_116804->Sup.len)) raiseIndexError();
if (!(((NU8)(Tail_116804->data[0])) == ((NU8)(92)) || ((NU8)(Tail_116804->data[0])) == ((NU8)(47)))) goto LA10;
F.line = 336;
LOC14 = copyStr(Tail_116804, 1);
LOC13 = rawNewString(Head_116803->Sup.len + LOC14->Sup.len + 0);
appendString(LOC13, Head_116803);
appendString(LOC13, LOC14);
Result_116805 = LOC13;
goto LA9;
LA10: ;
F.line = 338;
LOC16 = rawNewString(Head_116803->Sup.len + Tail_116804->Sup.len + 0);
appendString(LOC16, Head_116803);
appendString(LOC16, Tail_116804);
Result_116805 = LOC16;
LA9: ;
goto LA2;
LA6: ;
F.line = 340;
if ((NU)(0) > (NU)(Tail_116804->Sup.len)) raiseIndexError();
if (!(((NU8)(Tail_116804->data[0])) == ((NU8)(92)) || ((NU8)(Tail_116804->data[0])) == ((NU8)(47)))) goto LA19;
F.line = 341;
LOC22 = rawNewString(Head_116803->Sup.len + Tail_116804->Sup.len + 0);
appendString(LOC22, Head_116803);
appendString(LOC22, Tail_116804);
Result_116805 = LOC22;
goto LA18;
LA19: ;
F.line = 343;
LOC24 = rawNewString(Head_116803->Sup.len + Tail_116804->Sup.len + 1);
appendString(LOC24, Head_116803);
appendChar(LOC24, 92);
appendString(LOC24, Tail_116804);
Result_116805 = LOC24;
LA18: ;
LA2: ;
framePtr = framePtr->prev;
return Result_116805;
}
static N_INLINE(NI, addInt)(NI A_5203, NI B_5204) {
NI Result_5205;
NIM_BOOL LOC2;
Result_5205 = 0;
Result_5205 = (NI32)((NU32)(A_5203) + (NU32)(B_5204));
LOC2 = (0 <= (NI32)(Result_5205 ^ A_5203));
if (LOC2) goto LA3;
LOC2 = (0 <= (NI32)(Result_5205 ^ B_5204));
LA3: ;
if (!LOC2) goto LA4;
goto BeforeRet;
LA4: ;
raiseOverflow();
BeforeRet: ;
return Result_5205;
}
N_NIMCALL(void, Splitfile_117112)(NimStringDesc* Path_117114, TY117115* Result) {
NIM_BOOL LOC3;
NI Seppos_117139;
NI Dotpos_117142;
NI I_117152;
NI HEX3Atmp_117174;
NI Res_117176;
NIM_BOOL LOC21;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "os.splitFile";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\os.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
memset((void*)Result, 0, sizeof((*Result)));
F.line = 453;
LOC3 = (Path_117114->Sup.len == 0);
if (LOC3) goto LA4;
if ((NU)(subInt(Path_117114->Sup.len, 1)) > (NU)(Path_117114->Sup.len)) raiseIndexError();
LOC3 = (((NU8)(Path_117114->data[subInt(Path_117114->Sup.len, 1)])) == ((NU8)(92)) || ((NU8)(Path_117114->data[subInt(Path_117114->Sup.len, 1)])) == ((NU8)(47)));
LA4: ;
if (!LOC3) goto LA5;
F.line = 454;
unsureAsgnRef((void**) &(*Result).Dir, copyString(Path_117114));
unsureAsgnRef((void**) &(*Result).Name, copyString(((NimStringDesc*) &TMP124168)));
unsureAsgnRef((void**) &(*Result).Ext, copyString(((NimStringDesc*) &TMP124168)));
goto LA2;
LA5: ;
Seppos_117139 = 0;
F.line = 456;
Seppos_117139 = -1;
Dotpos_117142 = 0;
F.line = 457;
Dotpos_117142 = Path_117114->Sup.len;
I_117152 = 0;
HEX3Atmp_117174 = 0;
F.line = 458;
HEX3Atmp_117174 = subInt(Path_117114->Sup.len, 1);
Res_117176 = 0;
F.line = 1020;
Res_117176 = HEX3Atmp_117174;
F.line = 1021;
while (1) {
if (!(0 <= Res_117176)) goto LA13;
F.line = 1020;
I_117152 = Res_117176;
F.line = 459;
if ((NU)(I_117152) > (NU)(Path_117114->Sup.len)) raiseIndexError();
if (!((NU8)(Path_117114->data[I_117152]) == (NU8)(46))) goto LA17;
F.line = 460;
LOC21 = (Dotpos_117142 == Path_117114->Sup.len);
if (!(LOC21)) goto LA22;
LOC21 = (0 < I_117152);
LA22: ;
if (!LOC21) goto LA23;
F.line = 460;
Dotpos_117142 = I_117152;
LA23: ;
goto LA16;
LA17: ;
if ((NU)(I_117152) > (NU)(Path_117114->Sup.len)) raiseIndexError();
if (!(((NU8)(Path_117114->data[I_117152])) == ((NU8)(92)) || ((NU8)(Path_117114->data[I_117152])) == ((NU8)(47)))) goto LA26;
F.line = 462;
Seppos_117139 = I_117152;
F.line = 463;
goto LA13;
goto LA16;
LA26: ;
LA16: ;
F.line = 1023;
Res_117176 = subInt(Res_117176, 1);
} LA13: ;
F.line = 464;
unsureAsgnRef((void**) &(*Result).Dir, copyStrLast(Path_117114, 0, subInt(Seppos_117139, 1)));
F.line = 465;
unsureAsgnRef((void**) &(*Result).Name, copyStrLast(Path_117114, addInt(Seppos_117139, 1), subInt(Dotpos_117142, 1)));
F.line = 466;
unsureAsgnRef((void**) &(*Result).Ext, copyStr(Path_117114, Dotpos_117142));
LA2: ;
framePtr = framePtr->prev;
}
N_NOINLINE(void, osInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module os";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\os.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
F.line = 679;
Envcomputed_117820 = NIM_FALSE;
F.line = 680;
asgnRefNoCycle((void**) &Environment_117838, (TY3985*) newSeq(NTI3985, 0));
framePtr = framePtr->prev;
}

