/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\pure\times.o nimcache\lib\pure\times.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

#include <time.h>
typedef struct TY112402 TY112402;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TNimObject {
TNimType* m_type;
};
struct TY112402 {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY112504[7];
typedef NI TY112513[7];
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
N_NIMCALL(NIM_BOOL, HEX3C_112441)(NI32 A_112443, NI32 B_112444);
N_NIMCALL(NIM_BOOL, HEX3CHEX3D_112448)(NI32 A_112450, NI32 B_112451);
N_NIMCALL(TY112402, Tmtotimeinfo_112499)(struct tm* Tm_112501);
static N_INLINE(NI, chckRange)(NI I_4217, NI A_4218, NI B_4219);
N_NOINLINE(void, raiseRangeError)(NI64 Val_4818);
static N_INLINE(NI, addInt)(NI A_5203, NI B_5204);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(struct tm, Timeinfototm_112508)(TY112402* T_112510);
static N_INLINE(NI, subInt)(NI A_5403, NI B_5404);
N_NIMCALL(NI64, HEX2D_112437)(NI32 A_112439, NI32 B_112440);
N_NIMCALL(NI, Getstartmilsecs_112455)(void);
N_NIMCALL(NI32, Gettime_112416)(void);
N_NIMCALL(TY112402, Getlocaltime_112418)(NI32 T_112420);
N_NIMCALL(TY112402, Getgmtime_112421)(NI32 T_112423);
N_NIMCALL(NI32, Timeinfototime_112424)(TY112402* Timeinfo_112426);
N_NIMCALL(NimStringDesc*, Tostringtillnl_112549)(NCSTRING P_112551);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* Src_14308);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* S_14363, NIM_CHAR C_14364);
N_NIMCALL(NimStringDesc*, HEX24_112427)(TY112402* Timeinfo_112429);
N_NIMCALL(NimStringDesc*, HEX24_112430)(NI32 Time_112432);
N_NIMCALL(NI64, Unixtimetowintime_112585)(NI32 T_112587);
N_NIMCALL(NI64, mulInt64)(NI64 A_5179, NI64 B_5180);
static N_INLINE(NI64, addInt64)(NI64 A_5129, NI64 B_5130);
N_NIMCALL(NI32, Wintimetounixtime_112589)(NI64 T_112591);
static N_INLINE(NI64, subInt64)(NI64 A_5138, NI64 B_5139);
static N_INLINE(NI64, divInt64)(NI64 A_5161, NI64 B_5162);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI64, chckRange64)(NI64 I_4923, NI64 A_4924, NI64 B_4925);
N_NIMCALL(NimStringDesc*, Getdatestr_112433)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI Space_14287);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI X_15003);
static N_INLINE(void, appendString)(NimStringDesc* Dest_14392, NimStringDesc* Src_14393);
static N_INLINE(void, appendChar)(NimStringDesc* Dest_14409, NIM_CHAR C_14410);
N_NIMCALL(NimStringDesc*, Inttostr_109642)(NI X_109644, NI Minchars_109645);
N_NIMCALL(NimStringDesc*, Getclockstr_112435)(void);
NIM_CONST TY112504 Weekdays_112503 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
extern NIM_CONST TY112504 Weekdays_112503;
NIM_CONST TY112513 Weekdays_112512 = {1,
2,
3,
4,
5,
6,
0}
;
extern NIM_CONST TY112513 Weekdays_112512;
STRING_LITERAL(TMP112609, "", 0);
extern TNimType* NTI112402; /* TTimeInfo */
N_NIMCALL(NIM_BOOL, HEX3C_112441)(NI32 A_112443, NI32 B_112444) {
NIM_BOOL Result_112445;
NI64 LOC2;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.<";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112445 = 0;
F.line = 123;
LOC2 = HEX2D_112437(A_112443, B_112444);
Result_112445 = (LOC2 < 0);
framePtr = framePtr->prev;
return Result_112445;
}
N_NIMCALL(NIM_BOOL, HEX3CHEX3D_112448)(NI32 A_112450, NI32 B_112451) {
NIM_BOOL Result_112452;
NI64 LOC2;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.<=";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112452 = 0;
F.line = 127;
LOC2 = HEX2D_112437(A_112450, B_112451);
Result_112452 = (LOC2 <= 0);
framePtr = framePtr->prev;
return Result_112452;
}
static N_INLINE(NI, chckRange)(NI I_4217, NI A_4218, NI B_4219) {
NI Result_4916;
NIM_BOOL LOC2;
Result_4916 = 0;
LOC2 = (A_4218 <= I_4217);
if (!(LOC2)) goto LA3;
LOC2 = (I_4217 <= B_4219);
LA3: ;
if (!LOC2) goto LA4;
Result_4916 = I_4217;
goto BeforeRet;
goto LA1;
LA4: ;
raiseRangeError(((NI64) (I_4217)));
LA1: ;
BeforeRet: ;
return Result_4916;
}
static N_INLINE(NI, addInt)(NI A_5203, NI B_5204) {
NI Result_5205;
NIM_BOOL LOC2;
Result_5205 = 0;
Result_5205 = (NI32)((NU32)(A_5203) + (NU32)(B_5204));
LOC2 = (0 <= (NI32)(Result_5205 ^ A_5203));
if (LOC2) goto LA3;
LOC2 = (0 <= (NI32)(Result_5205 ^ B_5204));
LA3: ;
if (!LOC2) goto LA4;
goto BeforeRet;
LA4: ;
raiseOverflow();
BeforeRet: ;
return Result_5205;
}
N_NIMCALL(TY112402, Tmtotimeinfo_112499)(struct tm* Tm_112501) {
TY112402 Result_112502;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.tmToTimeInfo";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
memset((void*)&Result_112502, 0, sizeof(Result_112502));
Result_112502.Sup.m_type = NTI112402;
F.line = 174;
Result_112502.Second = ((NI) (((NI) ((*Tm_112501).tm_sec))));
F.line = 175;
Result_112502.Minute = ((NI) (((NI) ((*Tm_112501).tm_min))));
F.line = 176;
Result_112502.Hour = ((NI) (((NI) ((*Tm_112501).tm_hour))));
F.line = 177;
Result_112502.Monthday = ((NI) (((NI) ((*Tm_112501).tm_mday))));
F.line = 178;
Result_112502.Month = ((NU8)chckRange((*Tm_112501).tm_mon, ((NU8) 0), ((NU8) 11)));
F.line = 179;
Result_112502.Year = ((NI) (addInt((*Tm_112501).tm_year, ((NI32) 1900))));
F.line = 180;
if ((NU)(((NI) ((*Tm_112501).tm_wday))) > (NU)(6)) raiseIndexError();
Result_112502.Weekday = Weekdays_112503[(((NI) ((*Tm_112501).tm_wday)))-0];
F.line = 181;
Result_112502.Yearday = ((NI) (((NI) ((*Tm_112501).tm_yday))));
framePtr = framePtr->prev;
return Result_112502;
}
static N_INLINE(NI, subInt)(NI A_5403, NI B_5404) {
NI Result_5405;
NIM_BOOL LOC2;
Result_5405 = 0;
Result_5405 = (NI32)((NU32)(A_5403) - (NU32)(B_5404));
LOC2 = (0 <= (NI32)(Result_5405 ^ A_5403));
if (LOC2) goto LA3;
LOC2 = (0 <= (NI32)(Result_5405 ^ (NI32)((NU32) ~(B_5404))));
LA3: ;
if (!LOC2) goto LA4;
goto BeforeRet;
LA4: ;
raiseOverflow();
BeforeRet: ;
return Result_5405;
}
N_NIMCALL(struct tm, Timeinfototm_112508)(TY112402* T_112510) {
struct tm Result_112511;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.timeInfoToTM";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
memset((void*)&Result_112511, 0, sizeof(Result_112511));
F.line = 186;
Result_112511.tm_sec = ((NI32) ((*T_112510).Second));
F.line = 187;
Result_112511.tm_min = ((NI32) ((*T_112510).Minute));
F.line = 188;
Result_112511.tm_hour = ((NI32) ((*T_112510).Hour));
F.line = 189;
Result_112511.tm_mday = ((NI32) ((*T_112510).Monthday));
F.line = 190;
Result_112511.tm_mon = ((NI32) ((*T_112510).Month));
F.line = 191;
Result_112511.tm_year = ((NI32) (subInt((*T_112510).Year, 1900)));
F.line = 192;
Result_112511.tm_wday = ((NI32) (Weekdays_112512[((*T_112510).Weekday)-0]));
F.line = 193;
Result_112511.tm_yday = ((NI32) ((*T_112510).Yearday));
F.line = 194;
Result_112511.tm_isdst = ((NI32) -1);
framePtr = framePtr->prev;
return Result_112511;
}
N_NIMCALL(NI64, HEX2D_112437)(NI32 A_112439, NI32 B_112440) {
NI64 Result_112525;
NF LOC3;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.-";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112525 = 0;
F.line = 197;
F.line = 197;
LOC3 = difftime(A_112439, B_112440);
Result_112525 = float64ToInt64(((NF64) (LOC3)));
goto BeforeRet;
BeforeRet: ;
framePtr = framePtr->prev;
return Result_112525;
}
N_NIMCALL(NI, Getstartmilsecs_112455)(void) {
NI Result_112528;
NI LOC2;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.getStartMilsecs";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112528 = 0;
F.line = 202;
LOC2 = clock();
Result_112528 = float64ToInt32((((double) (((NI) (LOC2)))) / (((double) (CLOCKS_PER_SEC)) / 1000.00)));
framePtr = framePtr->prev;
return Result_112528;
}
N_NIMCALL(NI32, Gettime_112416)(void) {
NI32 Result_112531;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.getTime";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112531 = 0;
F.line = 204;
F.line = 204;
Result_112531 = time(0);
goto BeforeRet;
BeforeRet: ;
framePtr = framePtr->prev;
return Result_112531;
}
N_NIMCALL(TY112402, Getlocaltime_112418)(NI32 T_112420) {
TY112402 Result_112535;
NI32 A_112536;
struct tm* LOC3;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.getLocalTime";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
memset((void*)&Result_112535, 0, sizeof(Result_112535));
Result_112535.Sup.m_type = NTI112402;
A_112536 = 0;
F.line = 206;
A_112536 = T_112420;
F.line = 207;
LOC3 = localtime(&A_112536);
Result_112535 = Tmtotimeinfo_112499(&(*LOC3));
framePtr = framePtr->prev;
return Result_112535;
}
N_NIMCALL(TY112402, Getgmtime_112421)(NI32 T_112423) {
TY112402 Result_112541;
NI32 A_112542;
struct tm* LOC3;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.getGMTime";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
memset((void*)&Result_112541, 0, sizeof(Result_112541));
Result_112541.Sup.m_type = NTI112402;
A_112542 = 0;
F.line = 212;
A_112542 = T_112423;
F.line = 213;
LOC3 = gmtime(&A_112542);
Result_112541 = Tmtotimeinfo_112499(&(*LOC3));
framePtr = framePtr->prev;
return Result_112541;
}
N_NIMCALL(NI32, Timeinfototime_112424)(TY112402* Timeinfo_112426) {
NI32 Result_112547;
TY112402 Ctimeinfo_112548;
struct tm LOC4;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.TimeInfoToTime";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112547 = 0;
memset((void*)&Ctimeinfo_112548, 0, sizeof(Ctimeinfo_112548));
F.line = 218;
Ctimeinfo_112548 = (*Timeinfo_112426);
Ctimeinfo_112548.Sup.m_type = NTI112402;
F.line = 220;
F.line = 220;
LOC4 = Timeinfototm_112508(&Ctimeinfo_112548);
Result_112547 = mktime(&LOC4);
goto BeforeRet;
BeforeRet: ;
framePtr = framePtr->prev;
return Result_112547;
}
N_NIMCALL(NimStringDesc*, Tostringtillnl_112549)(NCSTRING P_112551) {
NimStringDesc* Result_112552;
NI I_112553;
NIM_BOOL LOC5;
NIM_BOOL LOC6;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.toStringTillNL";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112552 = 0;
F.line = 223;
Result_112552 = copyString(((NimStringDesc*) &TMP112609));
I_112553 = 0;
F.line = 224;
I_112553 = 0;
F.line = 225;
while (1) {
LOC6 = !(((NU8)(P_112551[I_112553]) == (NU8)(0)));
if (!(LOC6)) goto LA7;
LOC6 = !(((NU8)(P_112551[I_112553]) == (NU8)(10)));
LA7: ;
LOC5 = LOC6;
if (!(LOC5)) goto LA8;
LOC5 = !(((NU8)(P_112551[I_112553]) == (NU8)(13)));
LA8: ;
if (!LOC5) goto LA4;
F.line = 226;
Result_112552 = addChar(Result_112552, P_112551[I_112553]);
F.line = 227;
I_112553 = addInt(I_112553, 1);
} LA4: ;
F.line = 228;
goto BeforeRet;
BeforeRet: ;
framePtr = framePtr->prev;
return Result_112552;
}
N_NIMCALL(NimStringDesc*, HEX24_112427)(TY112402* Timeinfo_112429) {
NimStringDesc* Result_112575;
NCSTRING P_112576;
struct tm LOC2;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.$";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112575 = 0;
P_112576 = 0;
F.line = 232;
LOC2 = Timeinfototm_112508(Timeinfo_112429);
P_112576 = asctime(&LOC2);
F.line = 233;
Result_112575 = Tostringtillnl_112549(P_112576);
framePtr = framePtr->prev;
return Result_112575;
}
N_NIMCALL(NimStringDesc*, HEX24_112430)(NI32 Time_112432) {
NimStringDesc* Result_112580;
NI32 A_112581;
NCSTRING LOC4;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.$";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112580 = 0;
A_112581 = 0;
F.line = 237;
A_112581 = Time_112432;
F.line = 238;
F.line = 238;
LOC4 = ctime(&A_112581);
Result_112580 = Tostringtillnl_112549(LOC4);
goto BeforeRet;
BeforeRet: ;
framePtr = framePtr->prev;
return Result_112580;
}
static N_INLINE(NI64, addInt64)(NI64 A_5129, NI64 B_5130) {
NI64 Result_5131;
NIM_BOOL LOC2;
Result_5131 = 0;
Result_5131 = (NI64)((NU64)(A_5129) + (NU64)(B_5130));
LOC2 = (0 <= (Result_5131 ^ A_5129));
if (LOC2) goto LA3;
LOC2 = (0 <= (Result_5131 ^ B_5130));
LA3: ;
if (!LOC2) goto LA4;
goto BeforeRet;
LA4: ;
raiseOverflow();
BeforeRet: ;
return Result_5131;
}
N_NIMCALL(NI64, Unixtimetowintime_112585)(NI32 T_112587) {
NI64 Result_112588;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.unixTimeToWinTime";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112588 = 0;
F.line = 246;
Result_112588 = addInt64(mulInt64(((NI64) (T_112587)), 10000000), IL64(116444736000000000));
framePtr = framePtr->prev;
return Result_112588;
}
static N_INLINE(NI64, subInt64)(NI64 A_5138, NI64 B_5139) {
NI64 Result_5140;
NIM_BOOL LOC2;
Result_5140 = 0;
Result_5140 = (NI64)((NU64)(A_5138) - (NU64)(B_5139));
LOC2 = (0 <= (Result_5140 ^ A_5138));
if (LOC2) goto LA3;
LOC2 = (0 <= (Result_5140 ^ ~(B_5139)));
LA3: ;
if (!LOC2) goto LA4;
goto BeforeRet;
LA4: ;
raiseOverflow();
BeforeRet: ;
return Result_5140;
}
static N_INLINE(NI64, divInt64)(NI64 A_5161, NI64 B_5162) {
NI64 Result_5163;
NIM_BOOL LOC5;
Result_5163 = 0;
if (!(B_5162 == 0)) goto LA2;
raiseDivByZero();
LA2: ;
LOC5 = (A_5161 == (IL64(-9223372036854775807) - IL64(1)));
if (!(LOC5)) goto LA6;
LOC5 = (B_5162 == -1);
LA6: ;
if (!LOC5) goto LA7;
raiseOverflow();
LA7: ;
Result_5163 = (NI64)(A_5161 / B_5162);
goto BeforeRet;
BeforeRet: ;
return Result_5163;
}
N_NIMCALL(NI32, Wintimetounixtime_112589)(NI64 T_112591) {
NI32 Result_112592;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.winTimeToUnixTime";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112592 = 0;
F.line = 250;
Result_112592 = ((NI32)chckRange64(divInt64(subInt64(T_112591, IL64(116444736000000000)), 10000000), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
framePtr = framePtr->prev;
return Result_112592;
}
static N_INLINE(void, appendString)(NimStringDesc* Dest_14392, NimStringDesc* Src_14393) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "system.appendString";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\system\\sysstr.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
F.line = 149;
memcpy(((NCSTRING) (&(*Dest_14392).data[((*Dest_14392).Sup.len)-0])), ((NCSTRING) ((*Src_14393).data)), ((NI32) ((NI32)((NI32)((*Src_14393).Sup.len + 1) * 1))));
F.line = 150;
(*Dest_14392).Sup.len += (*Src_14393).Sup.len;
framePtr = framePtr->prev;
}
static N_INLINE(void, appendChar)(NimStringDesc* Dest_14409, NIM_CHAR C_14410) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "system.appendChar";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\system\\sysstr.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
F.line = 153;
(*Dest_14409).data[((*Dest_14409).Sup.len)-0] = C_14410;
F.line = 154;
(*Dest_14409).data[((NI32)((*Dest_14409).Sup.len + 1))-0] = 0;
F.line = 155;
(*Dest_14409).Sup.len += 1;
framePtr = framePtr->prev;
}
N_NIMCALL(NimStringDesc*, Getdatestr_112433)(void) {
NimStringDesc* Result_112612;
TY112402 Ti_112613;
NI32 LOC2;
NimStringDesc* LOC4;
NimStringDesc* LOC5;
NimStringDesc* LOC6;
NimStringDesc* LOC7;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.getDateStr";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112612 = 0;
memset((void*)&Ti_112613, 0, sizeof(Ti_112613));
F.line = 302;
LOC2 = Gettime_112416();
Ti_112613 = Getlocaltime_112418(LOC2);
Ti_112613.Sup.m_type = NTI112402;
F.line = 303;
LOC5 = nimIntToStr(Ti_112613.Year);
LOC6 = Inttostr_109642(addInt(Ti_112613.Month, 1), 2);
LOC7 = Inttostr_109642(((NI) (Ti_112613.Monthday)), 2);
LOC4 = rawNewString(LOC5->Sup.len + LOC6->Sup.len + LOC7->Sup.len + 2);
appendString(LOC4, LOC5);
appendChar(LOC4, 45);
appendString(LOC4, LOC6);
appendChar(LOC4, 45);
appendString(LOC4, LOC7);
Result_112612 = LOC4;
framePtr = framePtr->prev;
return Result_112612;
}
N_NIMCALL(NimStringDesc*, Getclockstr_112435)(void) {
NimStringDesc* Result_112647;
TY112402 Ti_112648;
NI32 LOC2;
NimStringDesc* LOC4;
NimStringDesc* LOC5;
NimStringDesc* LOC6;
NimStringDesc* LOC7;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "times.getClockStr";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_112647 = 0;
memset((void*)&Ti_112648, 0, sizeof(Ti_112648));
F.line = 307;
LOC2 = Gettime_112416();
Ti_112648 = Getlocaltime_112418(LOC2);
Ti_112648.Sup.m_type = NTI112402;
F.line = 308;
LOC5 = Inttostr_109642(((NI) (Ti_112648.Hour)), 2);
LOC6 = Inttostr_109642(((NI) (Ti_112648.Minute)), 2);
LOC7 = Inttostr_109642(((NI) (Ti_112648.Second)), 2);
LOC4 = rawNewString(LOC5->Sup.len + LOC6->Sup.len + LOC7->Sup.len + 2);
appendString(LOC4, LOC5);
appendChar(LOC4, 58);
appendString(LOC4, LOC6);
appendChar(LOC4, 58);
appendString(LOC4, LOC7);
Result_112647 = LOC4;
framePtr = framePtr->prev;
return Result_112647;
}
N_NOINLINE(void, timesInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module times";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\pure\\times.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
framePtr = framePtr->prev;
}

