/* Generated by Nimrod Compiler v0.8.6 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\newwrap\gtk\gdk2.o nimcache\lib\newwrap\gtk\gdk2.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

N_NOINLINE(void, gdk2Init)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module gdk2";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\newwrap\\gtk\\gdk2.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
framePtr = framePtr->prev;
}

