/* Generated by Nimrod Compiler v0.8.6 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\newwrap\gtk\pango.o nimcache\lib\newwrap\gtk\pango.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
typedef N_CDECL_PTR(void**, TY29140) (NCSTRING Str_29141);
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* Path_6670);
N_NIMCALL(void, nimUnloadLibrary)(void* Lib_6673);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* Path_6680);
N_NIMCALL(void*, nimGetProcAddr)(void* Lib_6676, NCSTRING Name_6677);
STRING_LITERAL(TMP124219, "libpango-1.0-0.dll", 18);
STRING_LITERAL(TMP124220, "libpango-1.0-0.dll", 18);
static void* TMP124218;
TY29140 Dl_29139;
N_NOINLINE(void, pangoInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module pango";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\newwrap\\gtk\\pango.nim";
F.line = 0;
framePtr = (TFrame*)&F;
if (!((TMP124218 = nimLoadLibrary((NimStringDesc*) &TMP124219))
)) nimLoadLibraryError((NimStringDesc*) &TMP124220);
Dl_29139 = (TY29140) nimGetProcAddr(TMP124218, "pango_font_description_from_string");
F.len = 0;
framePtr = framePtr->prev;
}

