/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\wrappers\gtk\gdk2pixbuf.o nimcache\lib\wrappers\gtk\gdk2pixbuf.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

N_NOINLINE(void, gdk2pixbufInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module gdk2pixbuf";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\wrappers\\gtk\\gdk2pixbuf.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
framePtr = framePtr->prev;
}

