/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\wrappers\gtk\pango.o nimcache\lib\wrappers\gtk\pango.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TY28248 TY28248;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
typedef N_CDECL_PTR(TY28248*, TY29142) (NCSTRING Str_29143);
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY28248 {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* Path_6470);
N_NIMCALL(void, nimUnloadLibrary)(void* Lib_6473);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* Path_6480);
N_NIMCALL(void*, nimGetProcAddr)(void* Lib_6476, NCSTRING Name_6477);
STRING_LITERAL(TMP124179, "libpango-1.0-0.dll", 18);
STRING_LITERAL(TMP124180, "libpango-1.0-0.dll", 18);
static void* TMP124178;
TY29142 Dl_29141;
N_NOINLINE(void, pangoInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module pango";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\wrappers\\gtk\\pango.nim";
F.line = 0;
framePtr = (TFrame*)&F;
if (!((TMP124178 = nimLoadLibrary((NimStringDesc*) &TMP124179))
)) nimLoadLibraryError((NimStringDesc*) &TMP124180);
Dl_29141 = (TY29142) nimGetProcAddr(TMP124178, "pango_font_description_from_string");
F.len = 0;
framePtr = framePtr->prev;
}

