/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\lib\windows\windows.o nimcache\lib\windows\windows.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TY80215 TY80215;
typedef struct TY75276 TY75276;
typedef struct TY75286 TY75286;
typedef struct TY75266 TY75266;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
typedef N_STDCALL_PTR(NI32, TY87565) (NI Hwnd_87566, NCSTRING Lptext_87567, NCSTRING Lpcaption_87568, NI Utype_87569);
typedef N_STDCALL_PTR(NI32, TY92997) (TY80215* Para1_92998);
typedef N_STDCALL_PTR(NI32, TY93000) (TY80215* Para1_93001);
typedef N_STDCALL_PTR(TY75276*, TY98090) (TY75286* Para1_98091);
typedef N_STDCALL_PTR(NI32, TY98113) (TY75276* Para1_98114, NCSTRING Para2_98115);
typedef N_STDCALL_PTR(NI, TY93866) (NI Hmem_93867);
typedef N_STDCALL_PTR(NI32, TY93863) (NI Hmem_93864);
typedef N_STDCALL_PTR(NI, TY93860) (void* Pmem_93861);
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_STDCALL_PTR(NI, TY68031) (NI Para1_68139, NI Para2_68140, NI Para3_68141, NI Para4_68142);
struct TY80215 {
NI32 Lstructsize;
NI Hwndowner;
NI Hinstance;
NCSTRING Lpstrfilter;
NCSTRING Lpstrcustomfilter;
NI32 Nmaxcustfilter;
NI32 Nfilterindex;
NCSTRING Lpstrfile;
NI32 Nmaxfile;
NCSTRING Lpstrfiletitle;
NI32 Nmaxfiletitle;
NCSTRING Lpstrinitialdir;
NCSTRING Lpstrtitle;
NI32 Flags;
NI16 Nfileoffset;
NI16 Nfileextension;
NCSTRING Lpstrdefext;
NI Lcustdata;
TY68031 Lpfnhook;
NCSTRING Lptemplatename;
void* Pvreserved;
NI32 Dwreserved;
NI32 Flagsex;
};
typedef NI8 TY75646[1];
struct TY75266 {
NI16 Cb;
TY75646 Abid;
};
struct TY75276 {
TY75266 Mkid;
};
typedef N_STDCALL_PTR(NI32, TY68017) (NI Para1_68114, NI Para2_68115, NI Para3_68116, NI Para4_68117);
struct TY75286 {
NI Hwndowner;
TY75276* Pidlroot;
NCSTRING Pszdisplayname;
NCSTRING Lpsztitle;
NI Ulflags;
TY68017 Lpfn;
NI Lparam;
NI32 Iimage;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* Path_6470);
N_NIMCALL(void, nimUnloadLibrary)(void* Lib_6473);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* Path_6480);
N_NIMCALL(void*, nimGetProcAddr)(void* Lib_6476, NCSTRING Name_6477);
N_NIMCALL(void*, Globalunlockptr_99430)(void* Lp_99432);
STRING_LITERAL(TMP122402, "user32", 6);
STRING_LITERAL(TMP122403, "user32", 6);
STRING_LITERAL(TMP123002, "comdlg32", 8);
STRING_LITERAL(TMP123003, "comdlg32", 8);
STRING_LITERAL(TMP123602, "shell32", 7);
STRING_LITERAL(TMP123603, "shell32", 7);
STRING_LITERAL(TMP123605, "kernel32", 8);
STRING_LITERAL(TMP123606, "kernel32", 8);
static void* TMP122401;
TY87565 Dl_87564;
static void* TMP123001;
TY92997 Dl_92996;
TY93000 Dl_92999;
static void* TMP123601;
TY98090 Dl_98089;
TY98113 Dl_98112;
static void* TMP123604;
TY93866 Dl_93865;
TY93863 Dl_93862;
TY93860 Dl_93859;
N_NIMCALL(void*, Globalunlockptr_99430)(void* Lp_99432) {
void* Result_104421;
NI LOC2;
NI32 LOC3;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "windows.GlobalUnlockPtr";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\windows\\windows.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_104421 = 0;
F.line = 23191;
LOC2 = Dl_93859(Lp_99432);
LOC3 = Dl_93862(LOC2);
F.line = 23192;
Result_104421 = Lp_99432;
framePtr = framePtr->prev;
return Result_104421;
}
N_NIMCALL(void*, Globalfreeptr_99427)(void* Lp_99429) {
void* Result_104417;
void* LOC2;
NI LOC3;
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "windows.GlobalFreePtr";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\windows\\windows.nim";
F.line = 0;
framePtr = (TFrame*)&F;
F.len = 0;
Result_104417 = 0;
F.line = 23188;
LOC2 = Globalunlockptr_99430(Lp_99429);
LOC3 = Dl_93865(((NI) (LOC2)));
Result_104417 = ((void*) (LOC3));
framePtr = framePtr->prev;
return Result_104417;
}
N_NOINLINE(void, windowsInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module windows";
F.prev = framePtr;
F.filename = "C:\\Programy\\nimrod\\lib\\windows\\windows.nim";
F.line = 0;
framePtr = (TFrame*)&F;
if (!((TMP122401 = nimLoadLibrary((NimStringDesc*) &TMP122402))
)) nimLoadLibraryError((NimStringDesc*) &TMP122403);
Dl_87564 = (TY87565) nimGetProcAddr(TMP122401, "MessageBoxA");
if (!((TMP123001 = nimLoadLibrary((NimStringDesc*) &TMP123002))
)) nimLoadLibraryError((NimStringDesc*) &TMP123003);
Dl_92996 = (TY92997) nimGetProcAddr(TMP123001, "GetOpenFileNameA");
Dl_92999 = (TY93000) nimGetProcAddr(TMP123001, "GetSaveFileNameA");
if (!((TMP123601 = nimLoadLibrary((NimStringDesc*) &TMP123602))
)) nimLoadLibraryError((NimStringDesc*) &TMP123603);
Dl_98089 = (TY98090) nimGetProcAddr(TMP123601, "SHBrowseForFolder");
Dl_98112 = (TY98113) nimGetProcAddr(TMP123601, "SHGetPathFromIDList");
if (!((TMP123604 = nimLoadLibrary((NimStringDesc*) &TMP123605))
)) nimLoadLibraryError((NimStringDesc*) &TMP123606);
Dl_93865 = (TY93866) nimGetProcAddr(TMP123604, "GlobalFree");
Dl_93862 = (TY93863) nimGetProcAddr(TMP123604, "GlobalUnlock");
Dl_93859 = (TY93860) nimGetProcAddr(TMP123604, "GlobalHandle");
F.len = 0;
framePtr = framePtr->prev;
}

