/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\gtksourceview.o nimcache\gtksourceview.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TY38465 TY38465;
typedef struct TY66006 TY66006;
typedef struct TY66010 TY66010;
typedef struct TY66014 TY66014;
typedef struct TY66018 TY66018;
typedef struct TY39645 TY39645;
typedef struct TY38407 TY38407;
typedef struct TY18896 TY18896;
typedef struct TY17358 TY17358;
typedef struct TY17354 TY17354;
typedef struct TY39133 TY39133;
typedef struct TY38463 TY38463;
typedef struct TY31326 TY31326;
typedef struct TY31220 TY31220;
typedef struct TY39719 TY39719;
typedef struct TY17380 TY17380;
typedef struct TY39755 TY39755;
typedef struct TY38511 TY38511;
typedef struct TY39729 TY39729;
typedef struct TY28284 TY28284;
typedef struct TY38573 TY38573;
typedef struct TY39653 TY39653;
typedef struct TY38959 TY38959;
typedef struct TY31214 TY31214;
typedef struct TY28248 TY28248;
typedef struct TY31276 TY31276;
typedef struct TY31352 TY31352;
typedef struct TY31240 TY31240;
typedef struct TY39115 TY39115;
typedef struct TY39641 TY39641;
typedef struct TY28272 TY28272;
typedef struct TY39743 TY39743;
typedef struct TY28252 TY28252;
typedef struct TY31346 TY31346;
typedef struct TY31298 TY31298;
typedef struct TY39639 TY39639;
typedef struct TY28294 TY28294;
typedef struct TY28260 TY28260;
typedef struct TY39713 TY39713;
typedef struct TY39691 TY39691;
typedef struct TY39711 TY39711;
typedef struct TY39707 TY39707;
typedef struct TY39677 TY39677;
typedef struct TY39665 TY39665;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
typedef N_CDECL_PTR(TY38465*, TY66022) (void);
typedef N_CDECL_PTR(TY66006*, TY66027) (void);
typedef N_CDECL_PTR(TY66006*, TY66029) (void);
typedef N_CDECL_PTR(TY66010*, TY66031) (TY66006* Lm_66032, NCSTRING Filename_66033, NCSTRING Contenttype_66034);
typedef N_CDECL_PTR(TY66010*, TY66036) (TY66006* Lm_66037, NCSTRING Id_66038);
typedef N_CDECL_PTR(void, TY66040) (TY66014* Buffer_66041, TY66010* Language_66042);
typedef N_CDECL_PTR(void, TY66044) (TY66014* Buffer_66045, NIM_BOOL Highlight_66046);
typedef N_CDECL_PTR(void, TY66048) (TY66018* View_66049, NIM_BOOL Enable_66050);
typedef N_CDECL_PTR(void, TY66052) (TY66018* View_66053, NI32 Width_66054);
typedef N_CDECL_PTR(void, TY66056) (TY66018* View_66057, NIM_BOOL Show_66058);
typedef N_CDECL_PTR(void, TY66060) (TY66018* View_66061, NIM_BOOL Show_66062);
typedef N_CDECL_PTR(TY66014*, TY66064) (TY39645* Table_66065);
typedef N_CDECL_PTR(TY66014*, TY66067) (TY66010* Language_66068);
typedef N_CDECL_PTR(void, TY66070) (TY66014* Buffer_66071);
typedef N_CDECL_PTR(void, TY66073) (TY66014* Buffer_66074);
typedef N_CDECL_PTR(NIM_BOOL, TY66076) (TY66014* Buffer_66077);
typedef N_CDECL_PTR(NIM_BOOL, TY66079) (TY66014* Buffer_66080);
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY17358 {
TY17354* Gclass;
};
struct TY18896 {
TY17358 Gtypeinstance;
NI32 Refcount;
void* Qdata;
};
struct TY38407 {
  TY18896 Sup;
NI32 Flags;
};
struct TY38463 {
NI32 Width;
NI32 Height;
};
struct TY31326 {
NI32 X;
NI32 Y;
NI32 Width;
NI32 Height;
};
struct TY38465 {
  TY38407 Sup;
NI16 Privateflags;
NI8 State;
NI8 Savedstate;
NCSTRING Name;
TY39133* Style;
TY38463 Requisition;
TY31326 Allocation;
TY31220* Window;
TY38465* Parent;
};
struct TY66006 {
char dummy;
};
struct TY66010 {
char dummy;
};
struct TY39719 {
  TY18896 Sup;
TY39645* Tagtable;
void* Btree;
TY17380* Clipboardcontentsbuffers;
TY17380* Selectionclipboards;
void* Logattrcache;
NI32 Useractioncount;
NI16 Textbufferflag0;
};
struct TY66014 {
  TY39719 Sup;
};
struct TY38511 {
  TY38465 Sup;
TY38465* Focuschild;
NI32 Containerflag0;
};
struct TY39755 {
  TY38511 Sup;
TY39729* Layout;
TY39719* Buffer;
NI32 Selectiondraghandler;
NI32 Scrolltimeout;
NI32 Pixelsabovelines;
NI32 Pixelsbelowlines;
NI32 Pixelsinsidewrap;
NI32 Wrapmode;
NI32 Justify;
NI32 Leftmargin;
NI32 Rightmargin;
NI32 Indent;
TY28284* Tabs;
NI16 Textviewflag0;
void* Textwindow;
void* Leftwindow;
void* Rightwindow;
void* Topwindow;
void* Bottomwindow;
TY38573* Hadjustment;
TY38573* Vadjustment;
NI32 Xoffset;
NI32 Yoffset;
NI32 Width;
NI32 Height;
NI32 Virtualcursorx;
NI32 Virtualcursory;
TY39653* Firstparamark;
NI32 Firstparapixels;
TY39653* Dndmark;
NI32 Blinktimeout;
NI32 Firstvalidateidle;
NI32 Incrementalvalidateidle;
TY38959* Imcontext;
TY38465* Popupmenu;
NI32 Dragstartx;
NI32 Dragstarty;
TY17380* Children;
void* Pendingscroll;
NI32 Pendingplacecursorbutton;
};
struct TY66018 {
  TY39755 Sup;
};
struct TY39645 {
  TY18896 Sup;
void* Hash;
TY17380* Anonymous;
NI32 Anoncount;
TY17380* Buffers;
};
struct TY17354 {
NI Gtype;
};
struct TY31214 {
NI32 Pixel;
NI16 Red;
NI16 Green;
NI16 Blue;
};
typedef TY31214 TY42275[5];
typedef TY31276* TY42304[5];
typedef TY31220* TY42330[5];
struct TY39133 {
  TY18896 Sup;
TY42275 Fg;
TY42275 Bg;
TY42275 Light;
TY42275 Dark;
TY42275 Mid;
TY42275 Text;
TY42275 Base;
TY42275 Textaa;
TY31214 Black;
TY31214 White;
TY28248* Fontdesc;
NI32 Xthickness;
NI32 Ythickness;
TY42304 Fggc;
TY42304 Bggc;
TY42304 Lightgc;
TY42304 Darkgc;
TY42304 Midgc;
TY42304 Textgc;
TY42304 Basegc;
TY42304 Textaagc;
TY31276* Blackgc;
TY31276* Whitegc;
TY42330 Bgpixmap;
NI32 Attachcount;
NI32 Depth;
TY31352* Colormap;
TY31240* Privatefont;
TY28248* Privatefontdesc;
TY39115* Rcstyle;
TY17380* Styles;
void* Propertycache;
TY17380* Iconfactories;
};
struct TY31220 {
  TY18896 Sup;
};
struct TY17380 {
void* Data;
TY17380* Next;
};
struct TY39729 {
  TY18896 Sup;
NI32 Screenwidth;
NI32 Width;
NI32 Height;
TY39719* Buffer;
TY39641* Defaultstyle;
TY28272* Ltrcontext;
TY28272* Rtlcontext;
TY39641* Onestylecache;
TY39743* Onedisplaycache;
NI32 Wraploopcount;
NI16 Textlayoutflag0;
NCSTRING Preeditstring;
TY28252* Preeditattrs;
NI32 Preeditlen;
NI32 Preeditcursor;
};
struct TY28284 {
char dummy;
};
struct TY38573 {
  TY38407 Sup;
NF64 Lower;
NF64 Upper;
NF64 Value;
NF64 Stepincrement;
NF64 Pageincrement;
NF64 Pagesize;
};
struct TY39653 {
  TY18896 Sup;
void* Segment;
};
struct TY38959 {
  TY18896 Sup;
};
struct TY28248 {
char dummy;
};
struct TY31276 {
  TY18896 Sup;
NI32 Clipxorigin;
NI32 Clipyorigin;
NI32 Tsxorigin;
NI32 Tsyorigin;
TY31352* Colormap;
};
struct TY31352 {
  TY18896 Sup;
NI32 Size;
TY31214* Colors;
TY31346* Visual;
void* Windowingdata;
TY31298* Screen;
};
struct TY31240 {
NU8 Type;
NI32 Ascent;
NI32 Descent;
};
typedef NCSTRING TY42173[5];
typedef NI32 TY42177[5];
struct TY39115 {
  TY18896 Sup;
NCSTRING Name;
TY42173 Bgpixmapname;
TY28248* Fontdesc;
TY42177 Colorflags;
TY42275 Fg;
TY42275 Bg;
TY42275 Text;
TY42275 Base;
NI32 Xthickness;
NI32 Ythickness;
void* Rcproperties;
TY17380* Rcstylelists;
TY17380* Iconfactories;
NI16 Rcstyleflag0;
};
struct TY39639 {
TY31214 Bgcolor;
TY31214 Fgcolor;
TY31220* Bgstipple;
TY31220* Fgstipple;
NI32 Rise;
void* Padding1;
NI16 Flag0;
};
struct TY39641 {
NI32 Refcount;
TY39639 Appearance;
NI32 Justification;
NI32 Direction;
TY28248* Font;
NF64 Fontscale;
NI32 Leftmargin;
NI32 Indent;
NI32 Rightmargin;
NI32 Pixelsabovelines;
NI32 Pixelsbelowlines;
NI32 Pixelsinsidewrap;
TY28284* Tabs;
NI32 Wrapmode;
TY28294* Language;
void* Padding1;
NI16 Flag0;
};
struct TY28272 {
char dummy;
};
struct TY39743 {
TY28260* Layout;
TY17380* Cursors;
TY17380* Shapedobjects;
NI32 Direction;
NI32 Width;
NI32 Totalwidth;
NI32 Height;
NI32 Xoffset;
NI32 Leftmargin;
NI32 Rightmargin;
NI32 Topmargin;
NI32 Bottommargin;
NI32 Insertindex;
NIM_BOOL Sizeonly;
TY39713* Line;
};
struct TY28252 {
char dummy;
};
struct TY31346 {
  TY18896 Sup;
NU8 Thetype;
NI32 Depth;
NU8 Byteorder;
NI32 Colormapsize;
NI32 Bitsperrgb;
NI32 Redmask;
NI32 Redshift;
NI32 Redprec;
NI32 Greenmask;
NI32 Greenshift;
NI32 Greenprec;
NI32 Bluemask;
NI32 Blueshift;
NI32 Blueprec;
TY31298* Screen;
};
struct TY31298 {
  TY18896 Sup;
};
struct TY28294 {
char dummy;
};
struct TY28260 {
char dummy;
};
struct TY39713 {
void* Parent;
TY39713* Next;
TY39691* Segments;
TY39711* Views;
};
struct TY39677 {
TY39665* Obj;
TY17380* Widgets;
void* Tree;
TY39713* Line;
};
struct TY39691 {
TY39707* Type;
TY39691* Next;
NI32 Charcount;
NI32 Bytecount;
TY39677 Body;
};
struct TY39711 {
void* Viewid;
TY39711* Next;
NI32 Height;
NI32 Flag0;
};
typedef N_CDECL_PTR(NIM_BOOL, TY39697) (TY39691* Seg_43940, TY39713* Line_43941, NIM_BOOL Treegone_43942);
typedef N_CDECL_PTR(void, TY39703) (TY39691* Seg_43944, TY39713* Line_43945);
typedef N_CDECL_PTR(void, TY39705) (TY39691* Seg_43947, TY39713* Line_43948);
struct TY39707 {
NCSTRING Name;
NIM_BOOL Leftgravity;
TY39691 Splitfunc;
TY39697 Deletefunc;
TY39691 Cleanupfunc;
TY39703 Linechangefunc;
TY39705 Checkfunc;
};
struct TY39665 {
  TY18896 Sup;
void* Segment;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* Path_6470);
N_NIMCALL(void, nimUnloadLibrary)(void* Lib_6473);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* Path_6480);
N_NIMCALL(void*, nimGetProcAddr)(void* Lib_6476, NCSTRING Name_6477);
STRING_LITERAL(TMP66024, "libgtksourceview-2.0-0.dll", 26);
STRING_LITERAL(TMP66025, "libgtksourceview-2.0-0.dll", 26);
static void* TMP66023;
TY66022 Dl_66021;
TY66027 Dl_66026;
TY66029 Dl_66028;
TY66031 Dl_66030;
TY66036 Dl_66035;
TY66040 Dl_66039;
TY66044 Dl_66043;
TY66048 Dl_66047;
TY66052 Dl_66051;
TY66056 Dl_66055;
TY66060 Dl_66059;
TY66064 Dl_66063;
TY66067 Dl_66066;
TY66070 Dl_66069;
TY66073 Dl_66072;
TY66076 Dl_66075;
TY66079 Dl_66078;
N_NOINLINE(void, gtksourceviewInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
F.procname = "module gtksourceview";
F.prev = framePtr;
F.filename = "gtksourceview.nim";
F.line = 0;
framePtr = (TFrame*)&F;
if (!((TMP66023 = nimLoadLibrary((NimStringDesc*) &TMP66024))
)) nimLoadLibraryError((NimStringDesc*) &TMP66025);
Dl_66021 = (TY66022) nimGetProcAddr(TMP66023, "gtk_source_view_new");
Dl_66026 = (TY66027) nimGetProcAddr(TMP66023, "gtk_source_language_manager_get_default");
Dl_66028 = (TY66029) nimGetProcAddr(TMP66023, "gtk_source_language_manager_new");
Dl_66030 = (TY66031) nimGetProcAddr(TMP66023, "gtk_source_language_manager_guess_language");
Dl_66035 = (TY66036) nimGetProcAddr(TMP66023, "gtk_source_language_manager_get_language");
Dl_66039 = (TY66040) nimGetProcAddr(TMP66023, "gtk_source_buffer_set_language");
Dl_66043 = (TY66044) nimGetProcAddr(TMP66023, "gtk_source_buffer_set_highlight_syntax");
Dl_66047 = (TY66048) nimGetProcAddr(TMP66023, "gtk_source_view_set_insert_spaces_instead_of_tabs");
Dl_66051 = (TY66052) nimGetProcAddr(TMP66023, "gtk_source_view_set_indent_width");
Dl_66055 = (TY66056) nimGetProcAddr(TMP66023, "gtk_source_view_set_show_line_marks");
Dl_66059 = (TY66060) nimGetProcAddr(TMP66023, "gtk_source_view_set_show_line_numbers");
Dl_66063 = (TY66064) nimGetProcAddr(TMP66023, "gtk_source_buffer_new");
Dl_66066 = (TY66067) nimGetProcAddr(TMP66023, "gtk_source_buffer_new_with_language");
Dl_66069 = (TY66070) nimGetProcAddr(TMP66023, "gtk_source_buffer_undo");
Dl_66072 = (TY66073) nimGetProcAddr(TMP66023, "gtk_source_buffer_redo");
Dl_66075 = (TY66076) nimGetProcAddr(TMP66023, "gtk_source_buffer_can_undo");
Dl_66078 = (TY66079) nimGetProcAddr(TMP66023, "gtk_source_buffer_can_redo");
F.len = 0;
framePtr = framePtr->prev;
}

