/* Generated by Nimrod Compiler v0.8.8 */
/*   (c) 2009 Andreas Rumpf */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   C:\Programy\nimrod\dist\mingw\bin\gcc.exe -c  -w  -IC:\Programy\nimrod\lib -o nimcache\nim__dat.o nimcache\nim__dat.c */

typedef long int NI;
typedef unsigned long int NU;
#include "nimbase.h"

#include <signal.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef struct E_Base E_Base;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY416 TY416;
typedef struct TY418 TY418;
typedef struct TY420 TY420;
typedef struct TY442 TY442;
typedef struct TY428 TY428;
typedef struct EOverflow EOverflow;
typedef struct TY3985 TY3985;
typedef struct TY452 TY452;
typedef struct EAssertionFailed EAssertionFailed;
typedef struct TY448 TY448;
typedef struct TY444 TY444;
typedef struct TY446 TY446;
typedef struct TY456 TY456;
typedef struct TY454 TY454;
typedef struct EDivByZero EDivByZero;
typedef struct TY458 TY458;
typedef struct EFloatInvalidOp EFloatInvalidOp;
typedef struct EFloatOverflow EFloatOverflow;
typedef struct EFloatUnderflow EFloatUnderflow;
typedef struct TY422 TY422;
typedef struct TY424 TY424;
typedef struct TY112402 TY112402;
typedef struct TY124002 TY124002;
typedef struct TY38531 TY38531;
typedef struct TY66010 TY66010;
typedef struct TY39403 TY39403;
typedef struct TY39571 TY39571;
typedef struct TY124009 TY124009;
typedef struct TY124004 TY124004;
typedef struct TY66014 TY66014;
typedef struct TY38465 TY38465;
typedef struct TY18896 TY18896;
typedef struct TY17358 TY17358;
typedef struct TY17354 TY17354;
typedef struct TY38407 TY38407;
typedef struct TY39133 TY39133;
typedef struct TY38463 TY38463;
typedef struct TY31326 TY31326;
typedef struct TY31220 TY31220;
typedef struct TY31214 TY31214;
typedef struct TY28248 TY28248;
typedef struct TY31276 TY31276;
typedef struct TY31352 TY31352;
typedef struct TY31240 TY31240;
typedef struct TY39115 TY39115;
typedef struct TY17380 TY17380;
typedef struct TY31346 TY31346;
typedef struct TY31298 TY31298;
typedef struct TY38511 TY38511;
typedef struct TY38519 TY38519;
typedef struct TY38537 TY38537;
typedef struct TY17384 TY17384;
typedef struct TY38629 TY38629;
typedef struct TY38871 TY38871;
typedef struct TY39719 TY39719;
typedef struct TY39645 TY39645;
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TNimObject {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI space;
};
typedef NIM_CHAR TY239[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY239 data;
};
struct E_Base {
  TNimObject Sup;
NCSTRING name;
NimStringDesc* message;
};
struct TY416 {
  E_Base Sup;
};
struct TY418 {
  TY416 Sup;
};
struct TY420 {
  TY418 Sup;
};
struct TY442 {
  TY418 Sup;
};
struct TY428 {
  TY416 Sup;
};
struct EOverflow {
  TY428 Sup;
};
struct TY452 {
  TY416 Sup;
};
struct EAssertionFailed {
  TY416 Sup;
};
struct TY448 {
  TY416 Sup;
};
struct TY444 {
  TY416 Sup;
};
struct TY446 {
  TY416 Sup;
};
struct TY456 {
  TY416 Sup;
};
struct TY454 {
  TY416 Sup;
};
struct EDivByZero {
  TY428 Sup;
};
struct TY458 {
  TY416 Sup;
};
struct EFloatInvalidOp {
  TY458 Sup;
};
struct EFloatOverflow {
  TY458 Sup;
};
struct EFloatUnderflow {
  TY458 Sup;
};
struct TY422 {
  TY418 Sup;
};
struct TY424 {
  TY422 Sup;
};
struct TY112402 {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
};
struct TY124004 {
TNimType* m_type;
TY66014* Buffer;
TY38465* Sourceview;
NIM_BOOL Saved;
NimStringDesc* Filename;
};
struct TY124002 {
TNimType* m_type;
TY38531* W;
TY66010* Nimlang;
TY39403* Sourceviewtabs;
TY39571* Bottombar;
TY124009* Tabs;
};
struct TY17358 {
TY17354* Gclass;
};
struct TY18896 {
TY17358 Gtypeinstance;
NI32 Refcount;
void* Qdata;
};
struct TY17354 {
NI Gtype;
};
struct TY38407 {
  TY18896 Sup;
NI32 Flags;
};
struct TY38463 {
NI32 Width;
NI32 Height;
};
struct TY31326 {
NI32 X;
NI32 Y;
NI32 Width;
NI32 Height;
};
struct TY38465 {
  TY38407 Sup;
NI16 Privateflags;
NI8 State;
NI8 Savedstate;
NCSTRING Name;
TY39133* Style;
TY38463 Requisition;
TY31326 Allocation;
TY31220* Window;
TY38465* Parent;
};
struct TY31214 {
NI32 Pixel;
NI16 Red;
NI16 Green;
NI16 Blue;
};
typedef TY31214 TY42275[5];
typedef TY31276* TY42304[5];
typedef TY31220* TY42330[5];
struct TY39133 {
  TY18896 Sup;
TY42275 Fg;
TY42275 Bg;
TY42275 Light;
TY42275 Dark;
TY42275 Mid;
TY42275 Text;
TY42275 Base;
TY42275 Textaa;
TY31214 Black;
TY31214 White;
TY28248* Fontdesc;
NI32 Xthickness;
NI32 Ythickness;
TY42304 Fggc;
TY42304 Bggc;
TY42304 Lightgc;
TY42304 Darkgc;
TY42304 Midgc;
TY42304 Textgc;
TY42304 Basegc;
TY42304 Textaagc;
TY31276* Blackgc;
TY31276* Whitegc;
TY42330 Bgpixmap;
NI32 Attachcount;
NI32 Depth;
TY31352* Colormap;
TY31240* Privatefont;
TY28248* Privatefontdesc;
TY39115* Rcstyle;
TY17380* Styles;
void* Propertycache;
TY17380* Iconfactories;
};
struct TY28248 {
char dummy;
};
struct TY31276 {
  TY18896 Sup;
NI32 Clipxorigin;
NI32 Clipyorigin;
NI32 Tsxorigin;
NI32 Tsyorigin;
TY31352* Colormap;
};
struct TY31352 {
  TY18896 Sup;
NI32 Size;
TY31214* Colors;
TY31346* Visual;
void* Windowingdata;
TY31298* Screen;
};
struct TY31346 {
  TY18896 Sup;
NU8 Thetype;
NI32 Depth;
NU8 Byteorder;
NI32 Colormapsize;
NI32 Bitsperrgb;
NI32 Redmask;
NI32 Redshift;
NI32 Redprec;
NI32 Greenmask;
NI32 Greenshift;
NI32 Greenprec;
NI32 Bluemask;
NI32 Blueshift;
NI32 Blueprec;
TY31298* Screen;
};
struct TY31298 {
  TY18896 Sup;
};
struct TY31220 {
  TY18896 Sup;
};
struct TY31240 {
NU8 Type;
NI32 Ascent;
NI32 Descent;
};
typedef NCSTRING TY42173[5];
typedef NI32 TY42177[5];
struct TY39115 {
  TY18896 Sup;
NCSTRING Name;
TY42173 Bgpixmapname;
TY28248* Fontdesc;
TY42177 Colorflags;
TY42275 Fg;
TY42275 Bg;
TY42275 Text;
TY42275 Base;
NI32 Xthickness;
NI32 Ythickness;
void* Rcproperties;
TY17380* Rcstylelists;
TY17380* Iconfactories;
NI16 Rcstyleflag0;
};
struct TY17380 {
void* Data;
TY17380* Next;
};
struct TY38511 {
  TY38465 Sup;
TY38465* Focuschild;
NI32 Containerflag0;
};
struct TY38519 {
  TY38511 Sup;
TY38465* Child;
};
struct TY38531 {
  TY38519 Sup;
NCSTRING Title;
NCSTRING Wmclassname;
NCSTRING Wmclassclass;
NCSTRING Wmrole;
TY38465* Focuswidget;
TY38465* Defaultwidget;
TY38531* Transientparent;
void* Geometryinfo;
TY31220* Frame;
TY38537* Group;
NI16 Configurerequestcount;
NI32 Windowflag0;
NI32 Frameleft;
NI32 Frametop;
NI32 Frameright;
NI32 Framebottom;
NI32 Keyschangedhandler;
NI32 Mnemonicmodifier;
TY31298* Screen;
};
struct TY38537 {
  TY18896 Sup;
TY17380* Grabs;
};
struct TY66010 {
char dummy;
};
struct TY39403 {
  TY38511 Sup;
void* Curpage;
TY17384* Children;
TY17384* Firsttab;
TY17384* Focustab;
TY38465* Menu;
TY31220* Eventwindow;
NI32 Timer;
NI16 Tabhborder;
NI16 Tabvborder;
NI16 Notebookflag0;
};
struct TY17384 {
void* Data;
TY17384* Next;
TY17384* Prev;
};
struct TY38629 {
  TY38511 Sup;
TY17384* Children;
NI16 Spacing;
NI16 Boxflag0;
};
struct TY38871 {
  TY38629 Sup;
};
struct TY39571 {
  TY38871 Sup;
TY38465* Frame;
TY38465* Label;
TY17380* Messages;
TY17380* Keys;
NI32 Seqcontextid;
NI32 Seqmessageid;
TY31220* Gripwindow;
NI16 Statusbarflag0;
};
struct TY39719 {
  TY18896 Sup;
TY39645* Tagtable;
void* Btree;
TY17380* Clipboardcontentsbuffers;
TY17380* Selectionclipboards;
void* Logattrcache;
NI32 Useractioncount;
NI16 Textbufferflag0;
};
struct TY39645 {
  TY18896 Sup;
void* Hash;
TY17380* Anonymous;
NI32 Anoncount;
TY17380* Buffers;
};
struct TY66014 {
  TY39719 Sup;
};
struct TY3985 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY124009 {
  TGenericSeq Sup;
  TY124004 data[SEQ_DECL_SIZE];
};
static N_INLINE(void, chckNil)(void* P_4227);
extern TNimType* NTI420; /* EIO */
extern TNimType* NTI418; /* ESystem */
extern TNimType* NTI416; /* ESynch */
extern TNimType* NTI412; /* E_Base */
extern TNimType* NTI408; /* TObject */
TNimType* NTI408; /* TObject */
TNimType* NTI412; /* E_Base */
extern TNimType* NTI132; /* cstring */
TNimType* NTI132; /* cstring */
extern TNimType* NTI130; /* string */
TNimType* NTI130; /* string */
TNimType* NTI416; /* ESynch */
TNimType* NTI418; /* ESystem */
TNimType* NTI420; /* EIO */
TNimType* NTI3870; /* ref EIO */
extern TNimType* NTI442; /* EOutOfMemory */
TNimType* NTI442; /* EOutOfMemory */
TNimType* NTI6725; /* ref EOutOfMemory */
extern TNimType* NTI432; /* EOverflow */
extern TNimType* NTI428; /* EArithmetic */
TNimType* NTI428; /* EArithmetic */
TNimType* NTI432; /* EOverflow */
TNimType* NTI5091; /* ref EOverflow */
TNimType* NTI3985; /* seq[string] */
extern TNimType* NTI452; /* ENoExceptionToReraise */
TNimType* NTI452; /* ENoExceptionToReraise */
TNimType* NTI4251; /* ref ENoExceptionToReraise */
extern TNimType* NTI436; /* EAssertionFailed */
TNimType* NTI436; /* EAssertionFailed */
TNimType* NTI4620; /* ref EAssertionFailed */
extern TNimType* NTI448; /* EOutOfRange */
TNimType* NTI448; /* EOutOfRange */
TNimType* NTI4819; /* ref EOutOfRange */
extern TNimType* NTI444; /* EInvalidIndex */
TNimType* NTI444; /* EInvalidIndex */
TNimType* NTI4856; /* ref EInvalidIndex */
extern TNimType* NTI446; /* EInvalidField */
TNimType* NTI446; /* EInvalidField */
TNimType* NTI4876; /* ref EInvalidField */
extern TNimType* NTI456; /* EInvalidObjectConversion */
TNimType* NTI456; /* EInvalidObjectConversion */
TNimType* NTI5007; /* ref EInvalidObjectConversion */
extern TNimType* NTI454; /* EInvalidObjectAssignment */
TNimType* NTI454; /* EInvalidObjectAssignment */
TNimType* NTI5037; /* ref EInvalidObjectAssignment */
extern TNimType* NTI430; /* EDivByZero */
TNimType* NTI430; /* EDivByZero */
TNimType* NTI5110; /* ref EDivByZero */
extern TNimType* NTI460; /* EFloatInvalidOp */
extern TNimType* NTI458; /* EFloatingPoint */
TNimType* NTI458; /* EFloatingPoint */
TNimType* NTI460; /* EFloatInvalidOp */
TNimType* NTI6403; /* ref EFloatInvalidOp */
extern TNimType* NTI464; /* EFloatOverflow */
TNimType* NTI464; /* EFloatOverflow */
TNimType* NTI6426; /* ref EFloatOverflow */
extern TNimType* NTI466; /* EFloatUnderflow */
TNimType* NTI466; /* EFloatUnderflow */
TNimType* NTI6443; /* ref EFloatUnderflow */
extern TNimType* NTI424; /* EInvalidLibrary */
extern TNimType* NTI422; /* EOS */
TNimType* NTI422; /* EOS */
TNimType* NTI424; /* EInvalidLibrary */
TNimType* NTI6481; /* ref EInvalidLibrary */
TNimType* NTI112402; /* TTimeInfo */
extern TNimType* NTI112403; /* range 0..61 */
extern TNimType* NTI108; /* int */
TNimType* NTI108; /* int */
TNimType* NTI112403; /* range 0..61 */
extern TNimType* NTI112405; /* range 0..59 */
TNimType* NTI112405; /* range 0..59 */
extern TNimType* NTI112407; /* range 0..23 */
TNimType* NTI112407; /* range 0..23 */
extern TNimType* NTI112409; /* range 1..31 */
TNimType* NTI112409; /* range 1..31 */
extern TNimType* NTI112005; /* TMonth */
TNimType* NTI112005; /* TMonth */
extern TNimType* NTI112007; /* TWeekDay */
TNimType* NTI112007; /* TWeekDay */
extern TNimType* NTI112414; /* range 0..365 */
TNimType* NTI112414; /* range 0..365 */
TNimType* NTI124002; /* MainWin */
extern TNimType* NTI38529; /* PWindow */
extern TNimType* NTI38531; /* TWindow */
extern TNimType* NTI38519; /* TBin */
extern TNimType* NTI38511; /* TContainer */
extern TNimType* NTI38465; /* TWidget */
extern TNimType* NTI38407; /* TObject */
extern TNimType* NTI18896; /* TGObject */
TNimType* NTI18896; /* TGObject */
extern TNimType* NTI17358; /* TGTypeInstance */
TNimType* NTI17358; /* TGTypeInstance */
extern TNimType* NTI17352; /* PGTypeClass */
extern TNimType* NTI17354; /* TGTypeClass */
TNimType* NTI17354; /* TGTypeClass */
TNimType* NTI17352; /* PGTypeClass */
extern TNimType* NTI114; /* int32 */
TNimType* NTI114; /* int32 */
extern TNimType* NTI134; /* pointer */
TNimType* NTI134; /* pointer */
TNimType* NTI38407; /* TObject */
TNimType* NTI38465; /* TWidget */
extern TNimType* NTI112; /* int16 */
TNimType* NTI112; /* int16 */
extern TNimType* NTI110; /* int8 */
TNimType* NTI110; /* int8 */
extern TNimType* NTI38367; /* PStyle */
extern TNimType* NTI39133; /* TStyle */
TNimType* NTI39133; /* TStyle */
extern TNimType* NTI42275; /* array[0..4, TColor] */
extern TNimType* NTI31214; /* TColor */
TNimType* NTI31214; /* TColor */
TNimType* NTI42275; /* array[0..4, TColor] */
extern TNimType* NTI28246; /* PFontDescription */
extern TNimType* NTI28248; /* TFontDescription */
TNimType* NTI28248; /* TFontDescription */
TNimType* NTI28246; /* PFontDescription */
extern TNimType* NTI42304; /* array[0..4, PGC] */
extern TNimType* NTI31274; /* PGC */
extern TNimType* NTI31276; /* TGC */
TNimType* NTI31276; /* TGC */
extern TNimType* NTI31216; /* PColormap */
extern TNimType* NTI31352; /* TColormap */
TNimType* NTI31352; /* TColormap */
extern TNimType* NTI31212; /* PColor */
TNimType* NTI31212; /* PColor */
extern TNimType* NTI31344; /* PVisual */
extern TNimType* NTI31346; /* TVisual */
TNimType* NTI31346; /* TVisual */
extern TNimType* NTI31342; /* TVisualType */
TNimType* NTI31342; /* TVisualType */
extern TNimType* NTI31334; /* TByteOrder */
TNimType* NTI31334; /* TByteOrder */
extern TNimType* NTI31296; /* PScreen */
extern TNimType* NTI31298; /* TScreen */
TNimType* NTI31298; /* TScreen */
TNimType* NTI31296; /* PScreen */
TNimType* NTI31344; /* PVisual */
TNimType* NTI31216; /* PColormap */
TNimType* NTI31274; /* PGC */
TNimType* NTI42304; /* array[0..4, PGC] */
extern TNimType* NTI42330; /* array[0..4, PPixmap] */
extern TNimType* NTI31222; /* PWindow */
extern TNimType* NTI31220; /* TWindow */
TNimType* NTI31220; /* TWindow */
TNimType* NTI31222; /* PWindow */
TNimType* NTI42330; /* array[0..4, PPixmap] */
extern TNimType* NTI31238; /* PFont */
extern TNimType* NTI31240; /* TFont */
TNimType* NTI31240; /* TFont */
extern TNimType* NTI31236; /* TFontType */
TNimType* NTI31236; /* TFontType */
TNimType* NTI31238; /* PFont */
extern TNimType* NTI39113; /* PRcStyle */
extern TNimType* NTI39115; /* TRcStyle */
TNimType* NTI39115; /* TRcStyle */
extern TNimType* NTI42173; /* array[0..4, cstring] */
TNimType* NTI42173; /* array[0..4, cstring] */
extern TNimType* NTI42177; /* array[0..4, TRcFlags] */
TNimType* NTI42177; /* array[0..4, TRcFlags] */
extern TNimType* NTI17376; /* PGSList */
extern TNimType* NTI17380; /* TGSList */
TNimType* NTI17380; /* TGSList */
TNimType* NTI17376; /* PGSList */
TNimType* NTI39113; /* PRcStyle */
TNimType* NTI38367; /* PStyle */
extern TNimType* NTI38463; /* TRequisition */
TNimType* NTI38463; /* TRequisition */
extern TNimType* NTI31326; /* TAllocation */
TNimType* NTI31326; /* TAllocation */
extern TNimType* NTI38213; /* PWidget */
TNimType* NTI38213; /* PWidget */
TNimType* NTI38511; /* TContainer */
TNimType* NTI38519; /* TBin */
TNimType* NTI38531; /* TWindow */
extern TNimType* NTI38527; /* PWindowGroup */
extern TNimType* NTI38537; /* TWindowGroup */
TNimType* NTI38537; /* TWindowGroup */
TNimType* NTI38527; /* PWindowGroup */
TNimType* NTI38529; /* PWindow */
extern TNimType* NTI66012; /* PSourceLanguage */
extern TNimType* NTI66010; /* TSourceLanguage */
TNimType* NTI66010; /* TSourceLanguage */
TNimType* NTI66012; /* PSourceLanguage */
extern TNimType* NTI39401; /* PNotebook */
extern TNimType* NTI39403; /* TNotebook */
TNimType* NTI39403; /* TNotebook */
extern TNimType* NTI17382; /* PGList */
extern TNimType* NTI17384; /* TGList */
TNimType* NTI17384; /* TGList */
TNimType* NTI17382; /* PGList */
TNimType* NTI39401; /* PNotebook */
extern TNimType* NTI39569; /* PStatusbar */
extern TNimType* NTI39571; /* TStatusbar */
extern TNimType* NTI38871; /* THBox */
extern TNimType* NTI38629; /* TBox */
TNimType* NTI38629; /* TBox */
TNimType* NTI38871; /* THBox */
TNimType* NTI39571; /* TStatusbar */
TNimType* NTI39569; /* PStatusbar */
extern TNimType* NTI124009; /* seq[Tab] */
extern TNimType* NTI124004; /* Tab */
TNimType* NTI124004; /* Tab */
extern TNimType* NTI66016; /* PSourceBuffer */
extern TNimType* NTI66014; /* TSourceBuffer */
extern TNimType* NTI39719; /* TTextBuffer */
TNimType* NTI39719; /* TTextBuffer */
extern TNimType* NTI38379; /* PTextTagTable */
extern TNimType* NTI39645; /* TTextTagTable */
TNimType* NTI39645; /* TTextTagTable */
TNimType* NTI38379; /* PTextTagTable */
TNimType* NTI66014; /* TSourceBuffer */
TNimType* NTI66016; /* PSourceBuffer */
extern TNimType* NTI124; /* bool */
TNimType* NTI124; /* bool */
TNimType* NTI124009; /* seq[Tab] */
static N_INLINE(void, chckNil)(void* P_4227) {
if (!(P_4227 == 0)) goto LA2;
raise(SIGSEGV);
LA2: ;
}
N_NOINLINE(void, nim__datInit)(void) {
volatile struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;
} F;
static TNimNode* TMP16706[2];
static TNimNode* TMP112602[8];
static TNimNode* TMP112603[12];
NI TMP112605;
static char* NIM_CONST TMP112604[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP112606[7];
NI TMP112608;
static char* NIM_CONST TMP112607[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode* TMP124016[5];
static TNimNode* TMP124017[3];
static TNimNode* TMP124018[9];
static TNimNode* TMP124019[33];
static TNimNode* TMP124020[4];
static TNimNode* TMP124021[5];
static TNimNode* TMP124022[5];
static TNimNode* TMP124023[15];
static TNimNode* TMP124024[6];
NI TMP124026;
static char* NIM_CONST TMP124025[6] = {
"VISUAL_STATIC_GRAY", 
"VISUAL_GRAYSCALE", 
"VISUAL_STATIC_COLOR", 
"VISUAL_PSEUDO_COLOR", 
"VISUAL_TRUE_COLOR", 
"VISUAL_DIRECT_COLOR"};
static TNimNode* TMP124027[2];
NI TMP124029;
static char* NIM_CONST TMP124028[2] = {
"LSB_FIRST", 
"MSB_FIRST"};
static TNimNode* TMP124030[3];
static TNimNode* TMP124031[2];
NI TMP124033;
static char* NIM_CONST TMP124032[2] = {
"FONT_FONT", 
"FONT_FONTSET"};
static TNimNode* TMP124034[14];
static TNimNode* TMP124035[2];
static TNimNode* TMP124036[2];
static TNimNode* TMP124037[4];
static TNimNode* TMP124038[2];
static TNimNode* TMP124039[19];
static TNimNode* TMP124040[10];
static TNimNode* TMP124041[3];
static TNimNode* TMP124042[3];
static TNimNode* TMP124043[8];
static TNimNode* TMP124044[4];
static TNimNode* TMP124045[7];
static TNimNode* TMP124046[4];
static TNimNode TMP103[264];
static TNimType TMP104[117];
F.procname = "module nim__dat";
F.prev = framePtr;
F.filename = "???";
F.line = 0;
framePtr = (TFrame*)&F;
NTI408 = &TMP104[0];
NTI412 = &TMP104[1];
NTI132 = &TMP104[2];
NTI130 = &TMP104[3];
NTI416 = &TMP104[4];
NTI418 = &TMP104[5];
NTI420 = &TMP104[6];
NTI3870 = &TMP104[7];
NTI442 = &TMP104[8];
NTI6725 = &TMP104[9];
NTI428 = &TMP104[10];
NTI432 = &TMP104[11];
NTI5091 = &TMP104[12];
NTI3985 = &TMP104[13];
NTI452 = &TMP104[14];
NTI4251 = &TMP104[15];
NTI436 = &TMP104[16];
NTI4620 = &TMP104[17];
NTI448 = &TMP104[18];
NTI4819 = &TMP104[19];
NTI444 = &TMP104[20];
NTI4856 = &TMP104[21];
NTI446 = &TMP104[22];
NTI4876 = &TMP104[23];
NTI456 = &TMP104[24];
NTI5007 = &TMP104[25];
NTI454 = &TMP104[26];
NTI5037 = &TMP104[27];
NTI430 = &TMP104[28];
NTI5110 = &TMP104[29];
NTI458 = &TMP104[30];
NTI460 = &TMP104[31];
NTI6403 = &TMP104[32];
NTI464 = &TMP104[33];
NTI6426 = &TMP104[34];
NTI466 = &TMP104[35];
NTI6443 = &TMP104[36];
NTI422 = &TMP104[37];
NTI424 = &TMP104[38];
NTI6481 = &TMP104[39];
NTI112402 = &TMP104[40];
NTI108 = &TMP104[41];
NTI112403 = &TMP104[42];
NTI112405 = &TMP104[43];
NTI112407 = &TMP104[44];
NTI112409 = &TMP104[45];
NTI112005 = &TMP104[46];
NTI112007 = &TMP104[47];
NTI112414 = &TMP104[48];
NTI124002 = &TMP104[49];
NTI18896 = &TMP104[50];
NTI17358 = &TMP104[51];
NTI17354 = &TMP104[52];
NTI17352 = &TMP104[53];
NTI114 = &TMP104[54];
NTI134 = &TMP104[55];
NTI38407 = &TMP104[56];
NTI38465 = &TMP104[57];
NTI112 = &TMP104[58];
NTI110 = &TMP104[59];
NTI39133 = &TMP104[60];
NTI31214 = &TMP104[61];
NTI42275 = &TMP104[62];
NTI28248 = &TMP104[63];
NTI28246 = &TMP104[64];
NTI31276 = &TMP104[65];
NTI31352 = &TMP104[66];
NTI31212 = &TMP104[67];
NTI31346 = &TMP104[68];
NTI31342 = &TMP104[69];
NTI31334 = &TMP104[70];
NTI31298 = &TMP104[71];
NTI31296 = &TMP104[72];
NTI31344 = &TMP104[73];
NTI31216 = &TMP104[74];
NTI31274 = &TMP104[75];
NTI42304 = &TMP104[76];
NTI31220 = &TMP104[77];
NTI31222 = &TMP104[78];
NTI42330 = &TMP104[79];
NTI31240 = &TMP104[80];
NTI31236 = &TMP104[81];
NTI31238 = &TMP104[82];
NTI39115 = &TMP104[83];
NTI42173 = &TMP104[84];
NTI42177 = &TMP104[85];
NTI17380 = &TMP104[86];
NTI17376 = &TMP104[87];
NTI39113 = &TMP104[88];
NTI38367 = &TMP104[89];
NTI38463 = &TMP104[90];
NTI31326 = &TMP104[91];
NTI38213 = &TMP104[92];
NTI38511 = &TMP104[93];
NTI38519 = &TMP104[94];
NTI38531 = &TMP104[95];
NTI38537 = &TMP104[96];
NTI38527 = &TMP104[97];
NTI38529 = &TMP104[98];
NTI66010 = &TMP104[99];
NTI66012 = &TMP104[100];
NTI39403 = &TMP104[101];
NTI17384 = &TMP104[102];
NTI17382 = &TMP104[103];
NTI39401 = &TMP104[104];
NTI38629 = &TMP104[105];
NTI38871 = &TMP104[106];
NTI39571 = &TMP104[107];
NTI39569 = &TMP104[108];
NTI124004 = &TMP104[109];
NTI39719 = &TMP104[110];
NTI39645 = &TMP104[111];
NTI38379 = &TMP104[112];
NTI66014 = &TMP104[113];
NTI66016 = &TMP104[114];
NTI124 = &TMP104[115];
NTI124009 = &TMP104[116];
NTI408->size = sizeof(TNimObject);
NTI408->kind = 17;
NTI408->base = 0;
NTI408->flags = 3;
TMP103[0].len = 0; TMP103[0].kind = 2;
NTI408->node = &TMP103[0];
NTI412->size = sizeof(E_Base);
NTI412->kind = 17;
NTI412->base = NTI408;
NTI412->flags = 2;
TMP16706[0] = &TMP103[2];
NTI132->size = sizeof(NCSTRING);
NTI132->kind = 29;
NTI132->base = 0;
NTI132->flags = 3;
TMP103[2].kind = 1;
TMP103[2].offset = offsetof(E_Base, name);
TMP103[2].typ = NTI132;
chckNil(TMP103[2].typ);
TMP103[2].name = "name";
TMP16706[1] = &TMP103[3];
NTI130->size = sizeof(NimStringDesc*);
NTI130->kind = 28;
NTI130->base = 0;
NTI130->flags = 2;
TMP103[3].kind = 1;
TMP103[3].offset = offsetof(E_Base, message);
TMP103[3].typ = NTI130;
chckNil(TMP103[3].typ);
TMP103[3].name = "msg";
TMP103[1].len = 2; TMP103[1].kind = 2; TMP103[1].sons = &TMP16706[0];
NTI412->node = &TMP103[1];
NTI416->size = sizeof(TY416);
NTI416->kind = 17;
NTI416->base = NTI412;
NTI416->flags = 2;
TMP103[4].len = 0; TMP103[4].kind = 2;
NTI416->node = &TMP103[4];
NTI418->size = sizeof(TY418);
NTI418->kind = 17;
NTI418->base = NTI416;
NTI418->flags = 2;
TMP103[5].len = 0; TMP103[5].kind = 2;
NTI418->node = &TMP103[5];
NTI420->size = sizeof(TY420);
NTI420->kind = 17;
NTI420->base = NTI418;
NTI420->flags = 2;
TMP103[6].len = 0; TMP103[6].kind = 2;
NTI420->node = &TMP103[6];
NTI3870->size = sizeof(TY420*);
NTI3870->kind = 22;
NTI3870->base = NTI420;
NTI3870->flags = 2;
NTI442->size = sizeof(TY442);
NTI442->kind = 17;
NTI442->base = NTI418;
NTI442->flags = 2;
TMP103[7].len = 0; TMP103[7].kind = 2;
NTI442->node = &TMP103[7];
NTI6725->size = sizeof(TY442*);
NTI6725->kind = 22;
NTI6725->base = NTI442;
NTI6725->flags = 2;
NTI428->size = sizeof(TY428);
NTI428->kind = 17;
NTI428->base = NTI416;
NTI428->flags = 2;
TMP103[8].len = 0; TMP103[8].kind = 2;
NTI428->node = &TMP103[8];
NTI432->size = sizeof(EOverflow);
NTI432->kind = 17;
NTI432->base = NTI428;
NTI432->flags = 2;
TMP103[9].len = 0; TMP103[9].kind = 2;
NTI432->node = &TMP103[9];
NTI5091->size = sizeof(EOverflow*);
NTI5091->kind = 22;
NTI5091->base = NTI432;
NTI5091->flags = 2;
NTI3985->size = sizeof(TY3985*);
NTI3985->kind = 24;
NTI3985->base = NTI130;
NTI3985->flags = 2;
NTI452->size = sizeof(TY452);
NTI452->kind = 17;
NTI452->base = NTI416;
NTI452->flags = 2;
TMP103[10].len = 0; TMP103[10].kind = 2;
NTI452->node = &TMP103[10];
NTI4251->size = sizeof(TY452*);
NTI4251->kind = 22;
NTI4251->base = NTI452;
NTI4251->flags = 2;
NTI436->size = sizeof(EAssertionFailed);
NTI436->kind = 17;
NTI436->base = NTI416;
NTI436->flags = 2;
TMP103[11].len = 0; TMP103[11].kind = 2;
NTI436->node = &TMP103[11];
NTI4620->size = sizeof(EAssertionFailed*);
NTI4620->kind = 22;
NTI4620->base = NTI436;
NTI4620->flags = 2;
NTI448->size = sizeof(TY448);
NTI448->kind = 17;
NTI448->base = NTI416;
NTI448->flags = 2;
TMP103[12].len = 0; TMP103[12].kind = 2;
NTI448->node = &TMP103[12];
NTI4819->size = sizeof(TY448*);
NTI4819->kind = 22;
NTI4819->base = NTI448;
NTI4819->flags = 2;
NTI444->size = sizeof(TY444);
NTI444->kind = 17;
NTI444->base = NTI416;
NTI444->flags = 2;
TMP103[13].len = 0; TMP103[13].kind = 2;
NTI444->node = &TMP103[13];
NTI4856->size = sizeof(TY444*);
NTI4856->kind = 22;
NTI4856->base = NTI444;
NTI4856->flags = 2;
NTI446->size = sizeof(TY446);
NTI446->kind = 17;
NTI446->base = NTI416;
NTI446->flags = 2;
TMP103[14].len = 0; TMP103[14].kind = 2;
NTI446->node = &TMP103[14];
NTI4876->size = sizeof(TY446*);
NTI4876->kind = 22;
NTI4876->base = NTI446;
NTI4876->flags = 2;
NTI456->size = sizeof(TY456);
NTI456->kind = 17;
NTI456->base = NTI416;
NTI456->flags = 2;
TMP103[15].len = 0; TMP103[15].kind = 2;
NTI456->node = &TMP103[15];
NTI5007->size = sizeof(TY456*);
NTI5007->kind = 22;
NTI5007->base = NTI456;
NTI5007->flags = 2;
NTI454->size = sizeof(TY454);
NTI454->kind = 17;
NTI454->base = NTI416;
NTI454->flags = 2;
TMP103[16].len = 0; TMP103[16].kind = 2;
NTI454->node = &TMP103[16];
NTI5037->size = sizeof(TY454*);
NTI5037->kind = 22;
NTI5037->base = NTI454;
NTI5037->flags = 2;
NTI430->size = sizeof(EDivByZero);
NTI430->kind = 17;
NTI430->base = NTI428;
NTI430->flags = 2;
TMP103[17].len = 0; TMP103[17].kind = 2;
NTI430->node = &TMP103[17];
NTI5110->size = sizeof(EDivByZero*);
NTI5110->kind = 22;
NTI5110->base = NTI430;
NTI5110->flags = 2;
NTI458->size = sizeof(TY458);
NTI458->kind = 17;
NTI458->base = NTI416;
NTI458->flags = 2;
TMP103[18].len = 0; TMP103[18].kind = 2;
NTI458->node = &TMP103[18];
NTI460->size = sizeof(EFloatInvalidOp);
NTI460->kind = 17;
NTI460->base = NTI458;
NTI460->flags = 2;
TMP103[19].len = 0; TMP103[19].kind = 2;
NTI460->node = &TMP103[19];
NTI6403->size = sizeof(EFloatInvalidOp*);
NTI6403->kind = 22;
NTI6403->base = NTI460;
NTI6403->flags = 2;
NTI464->size = sizeof(EFloatOverflow);
NTI464->kind = 17;
NTI464->base = NTI458;
NTI464->flags = 2;
TMP103[20].len = 0; TMP103[20].kind = 2;
NTI464->node = &TMP103[20];
NTI6426->size = sizeof(EFloatOverflow*);
NTI6426->kind = 22;
NTI6426->base = NTI464;
NTI6426->flags = 2;
NTI466->size = sizeof(EFloatUnderflow);
NTI466->kind = 17;
NTI466->base = NTI458;
NTI466->flags = 2;
TMP103[21].len = 0; TMP103[21].kind = 2;
NTI466->node = &TMP103[21];
NTI6443->size = sizeof(EFloatUnderflow*);
NTI6443->kind = 22;
NTI6443->base = NTI466;
NTI6443->flags = 2;
NTI422->size = sizeof(TY422);
NTI422->kind = 17;
NTI422->base = NTI418;
NTI422->flags = 2;
TMP103[22].len = 0; TMP103[22].kind = 2;
NTI422->node = &TMP103[22];
NTI424->size = sizeof(TY424);
NTI424->kind = 17;
NTI424->base = NTI422;
NTI424->flags = 2;
TMP103[23].len = 0; TMP103[23].kind = 2;
NTI424->node = &TMP103[23];
NTI6481->size = sizeof(TY424*);
NTI6481->kind = 22;
NTI6481->base = NTI424;
NTI6481->flags = 2;
NTI112402->size = sizeof(TY112402);
NTI112402->kind = 17;
NTI112402->base = NTI408;
NTI112402->flags = 3;
TMP112602[0] = &TMP103[25];
NTI108->size = sizeof(NI);
NTI108->kind = 31;
NTI108->base = 0;
NTI108->flags = 3;
NTI112403->size = sizeof(NI);
NTI112403->kind = 20;
NTI112403->base = NTI108;
NTI112403->flags = 3;
TMP103[25].kind = 1;
TMP103[25].offset = offsetof(TY112402, Second);
TMP103[25].typ = NTI112403;
chckNil(TMP103[25].typ);
TMP103[25].name = "second";
TMP112602[1] = &TMP103[26];
NTI112405->size = sizeof(NI);
NTI112405->kind = 20;
NTI112405->base = NTI108;
NTI112405->flags = 3;
TMP103[26].kind = 1;
TMP103[26].offset = offsetof(TY112402, Minute);
TMP103[26].typ = NTI112405;
chckNil(TMP103[26].typ);
TMP103[26].name = "minute";
TMP112602[2] = &TMP103[27];
NTI112407->size = sizeof(NI);
NTI112407->kind = 20;
NTI112407->base = NTI108;
NTI112407->flags = 3;
TMP103[27].kind = 1;
TMP103[27].offset = offsetof(TY112402, Hour);
TMP103[27].typ = NTI112407;
chckNil(TMP103[27].typ);
TMP103[27].name = "hour";
TMP112602[3] = &TMP103[28];
NTI112409->size = sizeof(NI);
NTI112409->kind = 20;
NTI112409->base = NTI108;
NTI112409->flags = 3;
TMP103[28].kind = 1;
TMP103[28].offset = offsetof(TY112402, Monthday);
TMP103[28].typ = NTI112409;
chckNil(TMP103[28].typ);
TMP103[28].name = "monthday";
TMP112602[4] = &TMP103[29];
NTI112005->size = sizeof(NU8);
NTI112005->kind = 14;
NTI112005->base = 0;
NTI112005->flags = 3;
for (TMP112605 = 0; TMP112605 < 12; TMP112605++) {
TMP103[TMP112605+30].kind = 1;
TMP103[TMP112605+30].offset = TMP112605;
TMP103[TMP112605+30].name = TMP112604[TMP112605];
TMP112603[TMP112605] = &TMP103[TMP112605+30];
}
TMP103[42].len = 12; TMP103[42].kind = 2; TMP103[42].sons = &TMP112603[0];
NTI112005->node = &TMP103[42];
TMP103[29].kind = 1;
TMP103[29].offset = offsetof(TY112402, Month);
TMP103[29].typ = NTI112005;
chckNil(TMP103[29].typ);
TMP103[29].name = "month";
TMP112602[5] = &TMP103[43];
TMP103[43].kind = 1;
TMP103[43].offset = offsetof(TY112402, Year);
TMP103[43].typ = NTI108;
chckNil(TMP103[43].typ);
TMP103[43].name = "year";
TMP112602[6] = &TMP103[44];
NTI112007->size = sizeof(NU8);
NTI112007->kind = 14;
NTI112007->base = 0;
NTI112007->flags = 3;
for (TMP112608 = 0; TMP112608 < 7; TMP112608++) {
TMP103[TMP112608+45].kind = 1;
TMP103[TMP112608+45].offset = TMP112608;
TMP103[TMP112608+45].name = TMP112607[TMP112608];
TMP112606[TMP112608] = &TMP103[TMP112608+45];
}
TMP103[52].len = 7; TMP103[52].kind = 2; TMP103[52].sons = &TMP112606[0];
NTI112007->node = &TMP103[52];
TMP103[44].kind = 1;
TMP103[44].offset = offsetof(TY112402, Weekday);
TMP103[44].typ = NTI112007;
chckNil(TMP103[44].typ);
TMP103[44].name = "weekday";
TMP112602[7] = &TMP103[53];
NTI112414->size = sizeof(NI);
NTI112414->kind = 20;
NTI112414->base = NTI108;
NTI112414->flags = 3;
TMP103[53].kind = 1;
TMP103[53].offset = offsetof(TY112402, Yearday);
TMP103[53].typ = NTI112414;
chckNil(TMP103[53].typ);
TMP103[53].name = "yearday";
TMP103[24].len = 8; TMP103[24].kind = 2; TMP103[24].sons = &TMP112602[0];
NTI112402->node = &TMP103[24];
NTI124002->size = sizeof(TY124002);
NTI124002->kind = 17;
NTI124002->base = 0;
NTI124002->flags = 2;
TMP124016[0] = &TMP103[55];
NTI18896->size = sizeof(TY18896);
NTI18896->kind = 17;
NTI18896->base = 0;
NTI18896->flags = 3;
TMP124017[0] = &TMP103[57];
NTI17358->size = sizeof(TY17358);
NTI17358->kind = 40;
NTI17358->base = 0;
NTI17358->flags = 3;
NTI17354->size = sizeof(TY17354);
NTI17354->kind = 40;
NTI17354->base = 0;
NTI17354->flags = 3;
TMP103[59].kind = 1;
TMP103[59].offset = offsetof(TY17354, Gtype);
TMP103[59].typ = NTI108;
chckNil(TMP103[59].typ);
TMP103[59].name = "g_type";
NTI17354->node = &TMP103[59];
NTI17352->size = sizeof(TY17354*);
NTI17352->kind = 21;
NTI17352->base = NTI17354;
NTI17352->flags = 3;
TMP103[58].kind = 1;
TMP103[58].offset = offsetof(TY17358, Gclass);
TMP103[58].typ = NTI17352;
chckNil(TMP103[58].typ);
TMP103[58].name = "g_class";
NTI17358->node = &TMP103[58];
TMP103[57].kind = 1;
TMP103[57].offset = offsetof(TY18896, Gtypeinstance);
TMP103[57].typ = NTI17358;
chckNil(TMP103[57].typ);
TMP103[57].name = "g_type_instance";
TMP124017[1] = &TMP103[60];
NTI114->size = sizeof(NI32);
NTI114->kind = 34;
NTI114->base = 0;
NTI114->flags = 3;
TMP103[60].kind = 1;
TMP103[60].offset = offsetof(TY18896, Refcount);
TMP103[60].typ = NTI114;
chckNil(TMP103[60].typ);
TMP103[60].name = "ref_count";
TMP124017[2] = &TMP103[61];
NTI134->size = sizeof(void*);
NTI134->kind = 26;
NTI134->base = 0;
NTI134->flags = 3;
TMP103[61].kind = 1;
TMP103[61].offset = offsetof(TY18896, Qdata);
TMP103[61].typ = NTI134;
chckNil(TMP103[61].typ);
TMP103[61].name = "qdata";
TMP103[56].len = 3; TMP103[56].kind = 2; TMP103[56].sons = &TMP124017[0];
NTI18896->node = &TMP103[56];
NTI38407->size = sizeof(TY38407);
NTI38407->kind = 17;
NTI38407->base = NTI18896;
NTI38407->flags = 3;
TMP103[62].kind = 1;
TMP103[62].offset = offsetof(TY38407, Flags);
TMP103[62].typ = NTI114;
chckNil(TMP103[62].typ);
TMP103[62].name = "flags";
NTI38407->node = &TMP103[62];
NTI38465->size = sizeof(TY38465);
NTI38465->kind = 17;
NTI38465->base = NTI38407;
NTI38465->flags = 3;
TMP124018[0] = &TMP103[64];
NTI112->size = sizeof(NI16);
NTI112->kind = 33;
NTI112->base = 0;
NTI112->flags = 3;
TMP103[64].kind = 1;
TMP103[64].offset = offsetof(TY38465, Privateflags);
TMP103[64].typ = NTI112;
chckNil(TMP103[64].typ);
TMP103[64].name = "private_flags";
TMP124018[1] = &TMP103[65];
NTI110->size = sizeof(NI8);
NTI110->kind = 32;
NTI110->base = 0;
NTI110->flags = 3;
TMP103[65].kind = 1;
TMP103[65].offset = offsetof(TY38465, State);
TMP103[65].typ = NTI110;
chckNil(TMP103[65].typ);
TMP103[65].name = "state";
TMP124018[2] = &TMP103[66];
TMP103[66].kind = 1;
TMP103[66].offset = offsetof(TY38465, Savedstate);
TMP103[66].typ = NTI110;
chckNil(TMP103[66].typ);
TMP103[66].name = "saved_state";
TMP124018[3] = &TMP103[67];
TMP103[67].kind = 1;
TMP103[67].offset = offsetof(TY38465, Name);
TMP103[67].typ = NTI132;
chckNil(TMP103[67].typ);
TMP103[67].name = "name";
TMP124018[4] = &TMP103[68];
NTI39133->size = sizeof(TY39133);
NTI39133->kind = 17;
NTI39133->base = NTI18896;
NTI39133->flags = 3;
TMP124019[0] = &TMP103[70];
NTI31214->size = sizeof(TY31214);
NTI31214->kind = 40;
NTI31214->base = 0;
NTI31214->flags = 3;
TMP124020[0] = &TMP103[72];
TMP103[72].kind = 1;
TMP103[72].offset = offsetof(TY31214, Pixel);
TMP103[72].typ = NTI114;
chckNil(TMP103[72].typ);
TMP103[72].name = "pixel";
TMP124020[1] = &TMP103[73];
TMP103[73].kind = 1;
TMP103[73].offset = offsetof(TY31214, Red);
TMP103[73].typ = NTI112;
chckNil(TMP103[73].typ);
TMP103[73].name = "red";
TMP124020[2] = &TMP103[74];
TMP103[74].kind = 1;
TMP103[74].offset = offsetof(TY31214, Green);
TMP103[74].typ = NTI112;
chckNil(TMP103[74].typ);
TMP103[74].name = "green";
TMP124020[3] = &TMP103[75];
TMP103[75].kind = 1;
TMP103[75].offset = offsetof(TY31214, Blue);
TMP103[75].typ = NTI112;
chckNil(TMP103[75].typ);
TMP103[75].name = "blue";
TMP103[71].len = 4; TMP103[71].kind = 2; TMP103[71].sons = &TMP124020[0];
NTI31214->node = &TMP103[71];
NTI42275->size = sizeof(TY42275);
NTI42275->kind = 16;
NTI42275->base = NTI31214;
NTI42275->flags = 3;
TMP103[70].kind = 1;
TMP103[70].offset = offsetof(TY39133, Fg);
TMP103[70].typ = NTI42275;
chckNil(TMP103[70].typ);
TMP103[70].name = "fg";
TMP124019[1] = &TMP103[76];
TMP103[76].kind = 1;
TMP103[76].offset = offsetof(TY39133, Bg);
TMP103[76].typ = NTI42275;
chckNil(TMP103[76].typ);
TMP103[76].name = "bg";
TMP124019[2] = &TMP103[77];
TMP103[77].kind = 1;
TMP103[77].offset = offsetof(TY39133, Light);
TMP103[77].typ = NTI42275;
chckNil(TMP103[77].typ);
TMP103[77].name = "light";
TMP124019[3] = &TMP103[78];
TMP103[78].kind = 1;
TMP103[78].offset = offsetof(TY39133, Dark);
TMP103[78].typ = NTI42275;
chckNil(TMP103[78].typ);
TMP103[78].name = "dark";
TMP124019[4] = &TMP103[79];
TMP103[79].kind = 1;
TMP103[79].offset = offsetof(TY39133, Mid);
TMP103[79].typ = NTI42275;
chckNil(TMP103[79].typ);
TMP103[79].name = "mid";
TMP124019[5] = &TMP103[80];
TMP103[80].kind = 1;
TMP103[80].offset = offsetof(TY39133, Text);
TMP103[80].typ = NTI42275;
chckNil(TMP103[80].typ);
TMP103[80].name = "text";
TMP124019[6] = &TMP103[81];
TMP103[81].kind = 1;
TMP103[81].offset = offsetof(TY39133, Base);
TMP103[81].typ = NTI42275;
chckNil(TMP103[81].typ);
TMP103[81].name = "base";
TMP124019[7] = &TMP103[82];
TMP103[82].kind = 1;
TMP103[82].offset = offsetof(TY39133, Textaa);
TMP103[82].typ = NTI42275;
chckNil(TMP103[82].typ);
TMP103[82].name = "text_aa";
TMP124019[8] = &TMP103[83];
TMP103[83].kind = 1;
TMP103[83].offset = offsetof(TY39133, Black);
TMP103[83].typ = NTI31214;
chckNil(TMP103[83].typ);
TMP103[83].name = "black";
TMP124019[9] = &TMP103[84];
TMP103[84].kind = 1;
TMP103[84].offset = offsetof(TY39133, White);
TMP103[84].typ = NTI31214;
chckNil(TMP103[84].typ);
TMP103[84].name = "white";
TMP124019[10] = &TMP103[85];
NTI28248->size = sizeof(TY28248);
NTI28248->kind = 40;
NTI28248->base = 0;
NTI28248->flags = 3;
TMP103[86].len = 0; TMP103[86].kind = 2;
NTI28248->node = &TMP103[86];
NTI28246->size = sizeof(TY28248*);
NTI28246->kind = 21;
NTI28246->base = NTI28248;
NTI28246->flags = 3;
TMP103[85].kind = 1;
TMP103[85].offset = offsetof(TY39133, Fontdesc);
TMP103[85].typ = NTI28246;
chckNil(TMP103[85].typ);
TMP103[85].name = "font_desc";
TMP124019[11] = &TMP103[87];
TMP103[87].kind = 1;
TMP103[87].offset = offsetof(TY39133, Xthickness);
TMP103[87].typ = NTI114;
chckNil(TMP103[87].typ);
TMP103[87].name = "xthickness";
TMP124019[12] = &TMP103[88];
TMP103[88].kind = 1;
TMP103[88].offset = offsetof(TY39133, Ythickness);
TMP103[88].typ = NTI114;
chckNil(TMP103[88].typ);
TMP103[88].name = "ythickness";
TMP124019[13] = &TMP103[89];
NTI31276->size = sizeof(TY31276);
NTI31276->kind = 17;
NTI31276->base = NTI18896;
NTI31276->flags = 3;
TMP124021[0] = &TMP103[91];
TMP103[91].kind = 1;
TMP103[91].offset = offsetof(TY31276, Clipxorigin);
TMP103[91].typ = NTI114;
chckNil(TMP103[91].typ);
TMP103[91].name = "clip_x_origin";
TMP124021[1] = &TMP103[92];
TMP103[92].kind = 1;
TMP103[92].offset = offsetof(TY31276, Clipyorigin);
TMP103[92].typ = NTI114;
chckNil(TMP103[92].typ);
TMP103[92].name = "clip_y_origin";
TMP124021[2] = &TMP103[93];
TMP103[93].kind = 1;
TMP103[93].offset = offsetof(TY31276, Tsxorigin);
TMP103[93].typ = NTI114;
chckNil(TMP103[93].typ);
TMP103[93].name = "ts_x_origin";
TMP124021[3] = &TMP103[94];
TMP103[94].kind = 1;
TMP103[94].offset = offsetof(TY31276, Tsyorigin);
TMP103[94].typ = NTI114;
chckNil(TMP103[94].typ);
TMP103[94].name = "ts_y_origin";
TMP124021[4] = &TMP103[95];
NTI31352->size = sizeof(TY31352);
NTI31352->kind = 17;
NTI31352->base = NTI18896;
NTI31352->flags = 3;
TMP124022[0] = &TMP103[97];
TMP103[97].kind = 1;
TMP103[97].offset = offsetof(TY31352, Size);
TMP103[97].typ = NTI114;
chckNil(TMP103[97].typ);
TMP103[97].name = "size";
TMP124022[1] = &TMP103[98];
NTI31212->size = sizeof(TY31214*);
NTI31212->kind = 21;
NTI31212->base = NTI31214;
NTI31212->flags = 3;
TMP103[98].kind = 1;
TMP103[98].offset = offsetof(TY31352, Colors);
TMP103[98].typ = NTI31212;
chckNil(TMP103[98].typ);
TMP103[98].name = "colors";
TMP124022[2] = &TMP103[99];
NTI31346->size = sizeof(TY31346);
NTI31346->kind = 17;
NTI31346->base = NTI18896;
NTI31346->flags = 3;
TMP124023[0] = &TMP103[101];
NTI31342->size = sizeof(NU8);
NTI31342->kind = 14;
NTI31342->base = 0;
NTI31342->flags = 3;
for (TMP124026 = 0; TMP124026 < 6; TMP124026++) {
TMP103[TMP124026+102].kind = 1;
TMP103[TMP124026+102].offset = TMP124026;
TMP103[TMP124026+102].name = TMP124025[TMP124026];
TMP124024[TMP124026] = &TMP103[TMP124026+102];
}
TMP103[108].len = 6; TMP103[108].kind = 2; TMP103[108].sons = &TMP124024[0];
NTI31342->node = &TMP103[108];
TMP103[101].kind = 1;
TMP103[101].offset = offsetof(TY31346, Thetype);
TMP103[101].typ = NTI31342;
chckNil(TMP103[101].typ);
TMP103[101].name = "TheType";
TMP124023[1] = &TMP103[109];
TMP103[109].kind = 1;
TMP103[109].offset = offsetof(TY31346, Depth);
TMP103[109].typ = NTI114;
chckNil(TMP103[109].typ);
TMP103[109].name = "depth";
TMP124023[2] = &TMP103[110];
NTI31334->size = sizeof(NU8);
NTI31334->kind = 14;
NTI31334->base = 0;
NTI31334->flags = 3;
for (TMP124029 = 0; TMP124029 < 2; TMP124029++) {
TMP103[TMP124029+111].kind = 1;
TMP103[TMP124029+111].offset = TMP124029;
TMP103[TMP124029+111].name = TMP124028[TMP124029];
TMP124027[TMP124029] = &TMP103[TMP124029+111];
}
TMP103[113].len = 2; TMP103[113].kind = 2; TMP103[113].sons = &TMP124027[0];
NTI31334->node = &TMP103[113];
TMP103[110].kind = 1;
TMP103[110].offset = offsetof(TY31346, Byteorder);
TMP103[110].typ = NTI31334;
chckNil(TMP103[110].typ);
TMP103[110].name = "byte_order";
TMP124023[3] = &TMP103[114];
TMP103[114].kind = 1;
TMP103[114].offset = offsetof(TY31346, Colormapsize);
TMP103[114].typ = NTI114;
chckNil(TMP103[114].typ);
TMP103[114].name = "colormap_size";
TMP124023[4] = &TMP103[115];
TMP103[115].kind = 1;
TMP103[115].offset = offsetof(TY31346, Bitsperrgb);
TMP103[115].typ = NTI114;
chckNil(TMP103[115].typ);
TMP103[115].name = "bits_per_rgb";
TMP124023[5] = &TMP103[116];
TMP103[116].kind = 1;
TMP103[116].offset = offsetof(TY31346, Redmask);
TMP103[116].typ = NTI114;
chckNil(TMP103[116].typ);
TMP103[116].name = "red_mask";
TMP124023[6] = &TMP103[117];
TMP103[117].kind = 1;
TMP103[117].offset = offsetof(TY31346, Redshift);
TMP103[117].typ = NTI114;
chckNil(TMP103[117].typ);
TMP103[117].name = "red_shift";
TMP124023[7] = &TMP103[118];
TMP103[118].kind = 1;
TMP103[118].offset = offsetof(TY31346, Redprec);
TMP103[118].typ = NTI114;
chckNil(TMP103[118].typ);
TMP103[118].name = "red_prec";
TMP124023[8] = &TMP103[119];
TMP103[119].kind = 1;
TMP103[119].offset = offsetof(TY31346, Greenmask);
TMP103[119].typ = NTI114;
chckNil(TMP103[119].typ);
TMP103[119].name = "green_mask";
TMP124023[9] = &TMP103[120];
TMP103[120].kind = 1;
TMP103[120].offset = offsetof(TY31346, Greenshift);
TMP103[120].typ = NTI114;
chckNil(TMP103[120].typ);
TMP103[120].name = "green_shift";
TMP124023[10] = &TMP103[121];
TMP103[121].kind = 1;
TMP103[121].offset = offsetof(TY31346, Greenprec);
TMP103[121].typ = NTI114;
chckNil(TMP103[121].typ);
TMP103[121].name = "green_prec";
TMP124023[11] = &TMP103[122];
TMP103[122].kind = 1;
TMP103[122].offset = offsetof(TY31346, Bluemask);
TMP103[122].typ = NTI114;
chckNil(TMP103[122].typ);
TMP103[122].name = "blue_mask";
TMP124023[12] = &TMP103[123];
TMP103[123].kind = 1;
TMP103[123].offset = offsetof(TY31346, Blueshift);
TMP103[123].typ = NTI114;
chckNil(TMP103[123].typ);
TMP103[123].name = "blue_shift";
TMP124023[13] = &TMP103[124];
TMP103[124].kind = 1;
TMP103[124].offset = offsetof(TY31346, Blueprec);
TMP103[124].typ = NTI114;
chckNil(TMP103[124].typ);
TMP103[124].name = "blue_prec";
TMP124023[14] = &TMP103[125];
NTI31298->size = sizeof(TY31298);
NTI31298->kind = 17;
NTI31298->base = NTI18896;
NTI31298->flags = 3;
TMP103[126].len = 0; TMP103[126].kind = 2;
NTI31298->node = &TMP103[126];
NTI31296->size = sizeof(TY31298*);
NTI31296->kind = 21;
NTI31296->base = NTI31298;
NTI31296->flags = 3;
TMP103[125].kind = 1;
TMP103[125].offset = offsetof(TY31346, Screen);
TMP103[125].typ = NTI31296;
chckNil(TMP103[125].typ);
TMP103[125].name = "screen";
TMP103[100].len = 15; TMP103[100].kind = 2; TMP103[100].sons = &TMP124023[0];
NTI31346->node = &TMP103[100];
NTI31344->size = sizeof(TY31346*);
NTI31344->kind = 21;
NTI31344->base = NTI31346;
NTI31344->flags = 3;
TMP103[99].kind = 1;
TMP103[99].offset = offsetof(TY31352, Visual);
TMP103[99].typ = NTI31344;
chckNil(TMP103[99].typ);
TMP103[99].name = "visual";
TMP124022[3] = &TMP103[127];
TMP103[127].kind = 1;
TMP103[127].offset = offsetof(TY31352, Windowingdata);
TMP103[127].typ = NTI134;
chckNil(TMP103[127].typ);
TMP103[127].name = "windowing_data";
TMP124022[4] = &TMP103[128];
TMP103[128].kind = 1;
TMP103[128].offset = offsetof(TY31352, Screen);
TMP103[128].typ = NTI31296;
chckNil(TMP103[128].typ);
TMP103[128].name = "screen";
TMP103[96].len = 5; TMP103[96].kind = 2; TMP103[96].sons = &TMP124022[0];
NTI31352->node = &TMP103[96];
NTI31216->size = sizeof(TY31352*);
NTI31216->kind = 21;
NTI31216->base = NTI31352;
NTI31216->flags = 3;
TMP103[95].kind = 1;
TMP103[95].offset = offsetof(TY31276, Colormap);
TMP103[95].typ = NTI31216;
chckNil(TMP103[95].typ);
TMP103[95].name = "colormap";
TMP103[90].len = 5; TMP103[90].kind = 2; TMP103[90].sons = &TMP124021[0];
NTI31276->node = &TMP103[90];
NTI31274->size = sizeof(TY31276*);
NTI31274->kind = 21;
NTI31274->base = NTI31276;
NTI31274->flags = 3;
NTI42304->size = sizeof(TY42304);
NTI42304->kind = 16;
NTI42304->base = NTI31274;
NTI42304->flags = 3;
TMP103[89].kind = 1;
TMP103[89].offset = offsetof(TY39133, Fggc);
TMP103[89].typ = NTI42304;
chckNil(TMP103[89].typ);
TMP103[89].name = "fg_gc";
TMP124019[14] = &TMP103[129];
TMP103[129].kind = 1;
TMP103[129].offset = offsetof(TY39133, Bggc);
TMP103[129].typ = NTI42304;
chckNil(TMP103[129].typ);
TMP103[129].name = "bg_gc";
TMP124019[15] = &TMP103[130];
TMP103[130].kind = 1;
TMP103[130].offset = offsetof(TY39133, Lightgc);
TMP103[130].typ = NTI42304;
chckNil(TMP103[130].typ);
TMP103[130].name = "light_gc";
TMP124019[16] = &TMP103[131];
TMP103[131].kind = 1;
TMP103[131].offset = offsetof(TY39133, Darkgc);
TMP103[131].typ = NTI42304;
chckNil(TMP103[131].typ);
TMP103[131].name = "dark_gc";
TMP124019[17] = &TMP103[132];
TMP103[132].kind = 1;
TMP103[132].offset = offsetof(TY39133, Midgc);
TMP103[132].typ = NTI42304;
chckNil(TMP103[132].typ);
TMP103[132].name = "mid_gc";
TMP124019[18] = &TMP103[133];
TMP103[133].kind = 1;
TMP103[133].offset = offsetof(TY39133, Textgc);
TMP103[133].typ = NTI42304;
chckNil(TMP103[133].typ);
TMP103[133].name = "text_gc";
TMP124019[19] = &TMP103[134];
TMP103[134].kind = 1;
TMP103[134].offset = offsetof(TY39133, Basegc);
TMP103[134].typ = NTI42304;
chckNil(TMP103[134].typ);
TMP103[134].name = "base_gc";
TMP124019[20] = &TMP103[135];
TMP103[135].kind = 1;
TMP103[135].offset = offsetof(TY39133, Textaagc);
TMP103[135].typ = NTI42304;
chckNil(TMP103[135].typ);
TMP103[135].name = "text_aa_gc";
TMP124019[21] = &TMP103[136];
TMP103[136].kind = 1;
TMP103[136].offset = offsetof(TY39133, Blackgc);
TMP103[136].typ = NTI31274;
chckNil(TMP103[136].typ);
TMP103[136].name = "black_gc";
TMP124019[22] = &TMP103[137];
TMP103[137].kind = 1;
TMP103[137].offset = offsetof(TY39133, Whitegc);
TMP103[137].typ = NTI31274;
chckNil(TMP103[137].typ);
TMP103[137].name = "white_gc";
TMP124019[23] = &TMP103[138];
NTI31220->size = sizeof(TY31220);
NTI31220->kind = 17;
NTI31220->base = NTI18896;
NTI31220->flags = 3;
TMP103[139].len = 0; TMP103[139].kind = 2;
NTI31220->node = &TMP103[139];
NTI31222->size = sizeof(TY31220*);
NTI31222->kind = 21;
NTI31222->base = NTI31220;
NTI31222->flags = 3;
NTI42330->size = sizeof(TY42330);
NTI42330->kind = 16;
NTI42330->base = NTI31222;
NTI42330->flags = 3;
TMP103[138].kind = 1;
TMP103[138].offset = offsetof(TY39133, Bgpixmap);
TMP103[138].typ = NTI42330;
chckNil(TMP103[138].typ);
TMP103[138].name = "bg_pixmap";
TMP124019[24] = &TMP103[140];
TMP103[140].kind = 1;
TMP103[140].offset = offsetof(TY39133, Attachcount);
TMP103[140].typ = NTI114;
chckNil(TMP103[140].typ);
TMP103[140].name = "attach_count";
TMP124019[25] = &TMP103[141];
TMP103[141].kind = 1;
TMP103[141].offset = offsetof(TY39133, Depth);
TMP103[141].typ = NTI114;
chckNil(TMP103[141].typ);
TMP103[141].name = "depth";
TMP124019[26] = &TMP103[142];
TMP103[142].kind = 1;
TMP103[142].offset = offsetof(TY39133, Colormap);
TMP103[142].typ = NTI31216;
chckNil(TMP103[142].typ);
TMP103[142].name = "colormap";
TMP124019[27] = &TMP103[143];
NTI31240->size = sizeof(TY31240);
NTI31240->kind = 40;
NTI31240->base = 0;
NTI31240->flags = 3;
TMP124030[0] = &TMP103[145];
NTI31236->size = sizeof(NU8);
NTI31236->kind = 14;
NTI31236->base = 0;
NTI31236->flags = 3;
for (TMP124033 = 0; TMP124033 < 2; TMP124033++) {
TMP103[TMP124033+146].kind = 1;
TMP103[TMP124033+146].offset = TMP124033;
TMP103[TMP124033+146].name = TMP124032[TMP124033];
TMP124031[TMP124033] = &TMP103[TMP124033+146];
}
TMP103[148].len = 2; TMP103[148].kind = 2; TMP103[148].sons = &TMP124031[0];
NTI31236->node = &TMP103[148];
TMP103[145].kind = 1;
TMP103[145].offset = offsetof(TY31240, Type);
TMP103[145].typ = NTI31236;
chckNil(TMP103[145].typ);
TMP103[145].name = "type";
TMP124030[1] = &TMP103[149];
TMP103[149].kind = 1;
TMP103[149].offset = offsetof(TY31240, Ascent);
TMP103[149].typ = NTI114;
chckNil(TMP103[149].typ);
TMP103[149].name = "ascent";
TMP124030[2] = &TMP103[150];
TMP103[150].kind = 1;
TMP103[150].offset = offsetof(TY31240, Descent);
TMP103[150].typ = NTI114;
chckNil(TMP103[150].typ);
TMP103[150].name = "descent";
TMP103[144].len = 3; TMP103[144].kind = 2; TMP103[144].sons = &TMP124030[0];
NTI31240->node = &TMP103[144];
NTI31238->size = sizeof(TY31240*);
NTI31238->kind = 21;
NTI31238->base = NTI31240;
NTI31238->flags = 3;
TMP103[143].kind = 1;
TMP103[143].offset = offsetof(TY39133, Privatefont);
TMP103[143].typ = NTI31238;
chckNil(TMP103[143].typ);
TMP103[143].name = "private_font";
TMP124019[28] = &TMP103[151];
TMP103[151].kind = 1;
TMP103[151].offset = offsetof(TY39133, Privatefontdesc);
TMP103[151].typ = NTI28246;
chckNil(TMP103[151].typ);
TMP103[151].name = "private_font_desc";
TMP124019[29] = &TMP103[152];
NTI39115->size = sizeof(TY39115);
NTI39115->kind = 17;
NTI39115->base = NTI18896;
NTI39115->flags = 3;
TMP124034[0] = &TMP103[154];
TMP103[154].kind = 1;
TMP103[154].offset = offsetof(TY39115, Name);
TMP103[154].typ = NTI132;
chckNil(TMP103[154].typ);
TMP103[154].name = "name";
TMP124034[1] = &TMP103[155];
NTI42173->size = sizeof(TY42173);
NTI42173->kind = 16;
NTI42173->base = NTI132;
NTI42173->flags = 3;
TMP103[155].kind = 1;
TMP103[155].offset = offsetof(TY39115, Bgpixmapname);
TMP103[155].typ = NTI42173;
chckNil(TMP103[155].typ);
TMP103[155].name = "bg_pixmap_name";
TMP124034[2] = &TMP103[156];
TMP103[156].kind = 1;
TMP103[156].offset = offsetof(TY39115, Fontdesc);
TMP103[156].typ = NTI28246;
chckNil(TMP103[156].typ);
TMP103[156].name = "font_desc";
TMP124034[3] = &TMP103[157];
NTI42177->size = sizeof(TY42177);
NTI42177->kind = 16;
NTI42177->base = NTI114;
NTI42177->flags = 3;
TMP103[157].kind = 1;
TMP103[157].offset = offsetof(TY39115, Colorflags);
TMP103[157].typ = NTI42177;
chckNil(TMP103[157].typ);
TMP103[157].name = "color_flags";
TMP124034[4] = &TMP103[158];
TMP103[158].kind = 1;
TMP103[158].offset = offsetof(TY39115, Fg);
TMP103[158].typ = NTI42275;
chckNil(TMP103[158].typ);
TMP103[158].name = "fg";
TMP124034[5] = &TMP103[159];
TMP103[159].kind = 1;
TMP103[159].offset = offsetof(TY39115, Bg);
TMP103[159].typ = NTI42275;
chckNil(TMP103[159].typ);
TMP103[159].name = "bg";
TMP124034[6] = &TMP103[160];
TMP103[160].kind = 1;
TMP103[160].offset = offsetof(TY39115, Text);
TMP103[160].typ = NTI42275;
chckNil(TMP103[160].typ);
TMP103[160].name = "text";
TMP124034[7] = &TMP103[161];
TMP103[161].kind = 1;
TMP103[161].offset = offsetof(TY39115, Base);
TMP103[161].typ = NTI42275;
chckNil(TMP103[161].typ);
TMP103[161].name = "base";
TMP124034[8] = &TMP103[162];
TMP103[162].kind = 1;
TMP103[162].offset = offsetof(TY39115, Xthickness);
TMP103[162].typ = NTI114;
chckNil(TMP103[162].typ);
TMP103[162].name = "xthickness";
TMP124034[9] = &TMP103[163];
TMP103[163].kind = 1;
TMP103[163].offset = offsetof(TY39115, Ythickness);
TMP103[163].typ = NTI114;
chckNil(TMP103[163].typ);
TMP103[163].name = "ythickness";
TMP124034[10] = &TMP103[164];
TMP103[164].kind = 1;
TMP103[164].offset = offsetof(TY39115, Rcproperties);
TMP103[164].typ = NTI134;
chckNil(TMP103[164].typ);
TMP103[164].name = "rc_properties";
TMP124034[11] = &TMP103[165];
NTI17380->size = sizeof(TY17380);
NTI17380->kind = 40;
NTI17380->base = 0;
NTI17380->flags = 3;
TMP124035[0] = &TMP103[167];
TMP103[167].kind = 1;
TMP103[167].offset = offsetof(TY17380, Data);
TMP103[167].typ = NTI134;
chckNil(TMP103[167].typ);
TMP103[167].name = "data";
TMP124035[1] = &TMP103[168];
TMP103[168].kind = 1;
TMP103[168].offset = offsetof(TY17380, Next);
TMP103[168].typ = NTI17376;
chckNil(TMP103[168].typ);
TMP103[168].name = "next";
TMP103[166].len = 2; TMP103[166].kind = 2; TMP103[166].sons = &TMP124035[0];
NTI17380->node = &TMP103[166];
NTI17376->size = sizeof(TY17380*);
NTI17376->kind = 21;
NTI17376->base = NTI17380;
NTI17376->flags = 3;
TMP103[165].kind = 1;
TMP103[165].offset = offsetof(TY39115, Rcstylelists);
TMP103[165].typ = NTI17376;
chckNil(TMP103[165].typ);
TMP103[165].name = "rc_style_lists";
TMP124034[12] = &TMP103[169];
TMP103[169].kind = 1;
TMP103[169].offset = offsetof(TY39115, Iconfactories);
TMP103[169].typ = NTI17376;
chckNil(TMP103[169].typ);
TMP103[169].name = "icon_factories";
TMP124034[13] = &TMP103[170];
TMP103[170].kind = 1;
TMP103[170].offset = offsetof(TY39115, Rcstyleflag0);
TMP103[170].typ = NTI112;
chckNil(TMP103[170].typ);
TMP103[170].name = "RcStyle_flag0";
TMP103[153].len = 14; TMP103[153].kind = 2; TMP103[153].sons = &TMP124034[0];
NTI39115->node = &TMP103[153];
NTI39113->size = sizeof(TY39115*);
NTI39113->kind = 21;
NTI39113->base = NTI39115;
NTI39113->flags = 3;
TMP103[152].kind = 1;
TMP103[152].offset = offsetof(TY39133, Rcstyle);
TMP103[152].typ = NTI39113;
chckNil(TMP103[152].typ);
TMP103[152].name = "rc_style";
TMP124019[30] = &TMP103[171];
TMP103[171].kind = 1;
TMP103[171].offset = offsetof(TY39133, Styles);
TMP103[171].typ = NTI17376;
chckNil(TMP103[171].typ);
TMP103[171].name = "styles";
TMP124019[31] = &TMP103[172];
TMP103[172].kind = 1;
TMP103[172].offset = offsetof(TY39133, Propertycache);
TMP103[172].typ = NTI134;
chckNil(TMP103[172].typ);
TMP103[172].name = "property_cache";
TMP124019[32] = &TMP103[173];
TMP103[173].kind = 1;
TMP103[173].offset = offsetof(TY39133, Iconfactories);
TMP103[173].typ = NTI17376;
chckNil(TMP103[173].typ);
TMP103[173].name = "icon_factories";
TMP103[69].len = 33; TMP103[69].kind = 2; TMP103[69].sons = &TMP124019[0];
NTI39133->node = &TMP103[69];
NTI38367->size = sizeof(TY39133*);
NTI38367->kind = 21;
NTI38367->base = NTI39133;
NTI38367->flags = 3;
TMP103[68].kind = 1;
TMP103[68].offset = offsetof(TY38465, Style);
TMP103[68].typ = NTI38367;
chckNil(TMP103[68].typ);
TMP103[68].name = "style";
TMP124018[5] = &TMP103[174];
NTI38463->size = sizeof(TY38463);
NTI38463->kind = 40;
NTI38463->base = 0;
NTI38463->flags = 3;
TMP124036[0] = &TMP103[176];
TMP103[176].kind = 1;
TMP103[176].offset = offsetof(TY38463, Width);
TMP103[176].typ = NTI114;
chckNil(TMP103[176].typ);
TMP103[176].name = "width";
TMP124036[1] = &TMP103[177];
TMP103[177].kind = 1;
TMP103[177].offset = offsetof(TY38463, Height);
TMP103[177].typ = NTI114;
chckNil(TMP103[177].typ);
TMP103[177].name = "height";
TMP103[175].len = 2; TMP103[175].kind = 2; TMP103[175].sons = &TMP124036[0];
NTI38463->node = &TMP103[175];
TMP103[174].kind = 1;
TMP103[174].offset = offsetof(TY38465, Requisition);
TMP103[174].typ = NTI38463;
chckNil(TMP103[174].typ);
TMP103[174].name = "requisition";
TMP124018[6] = &TMP103[178];
NTI31326->size = sizeof(TY31326);
NTI31326->kind = 40;
NTI31326->base = 0;
NTI31326->flags = 3;
TMP124037[0] = &TMP103[180];
TMP103[180].kind = 1;
TMP103[180].offset = offsetof(TY31326, X);
TMP103[180].typ = NTI114;
chckNil(TMP103[180].typ);
TMP103[180].name = "x";
TMP124037[1] = &TMP103[181];
TMP103[181].kind = 1;
TMP103[181].offset = offsetof(TY31326, Y);
TMP103[181].typ = NTI114;
chckNil(TMP103[181].typ);
TMP103[181].name = "y";
TMP124037[2] = &TMP103[182];
TMP103[182].kind = 1;
TMP103[182].offset = offsetof(TY31326, Width);
TMP103[182].typ = NTI114;
chckNil(TMP103[182].typ);
TMP103[182].name = "width";
TMP124037[3] = &TMP103[183];
TMP103[183].kind = 1;
TMP103[183].offset = offsetof(TY31326, Height);
TMP103[183].typ = NTI114;
chckNil(TMP103[183].typ);
TMP103[183].name = "height";
TMP103[179].len = 4; TMP103[179].kind = 2; TMP103[179].sons = &TMP124037[0];
NTI31326->node = &TMP103[179];
TMP103[178].kind = 1;
TMP103[178].offset = offsetof(TY38465, Allocation);
TMP103[178].typ = NTI31326;
chckNil(TMP103[178].typ);
TMP103[178].name = "allocation";
TMP124018[7] = &TMP103[184];
TMP103[184].kind = 1;
TMP103[184].offset = offsetof(TY38465, Window);
TMP103[184].typ = NTI31222;
chckNil(TMP103[184].typ);
TMP103[184].name = "window";
TMP124018[8] = &TMP103[185];
NTI38213->size = sizeof(TY38465*);
NTI38213->kind = 21;
NTI38213->base = NTI38465;
NTI38213->flags = 3;
TMP103[185].kind = 1;
TMP103[185].offset = offsetof(TY38465, Parent);
TMP103[185].typ = NTI38213;
chckNil(TMP103[185].typ);
TMP103[185].name = "parent";
TMP103[63].len = 9; TMP103[63].kind = 2; TMP103[63].sons = &TMP124018[0];
NTI38465->node = &TMP103[63];
NTI38511->size = sizeof(TY38511);
NTI38511->kind = 17;
NTI38511->base = NTI38465;
NTI38511->flags = 3;
TMP124038[0] = &TMP103[187];
TMP103[187].kind = 1;
TMP103[187].offset = offsetof(TY38511, Focuschild);
TMP103[187].typ = NTI38213;
chckNil(TMP103[187].typ);
TMP103[187].name = "focus_child";
TMP124038[1] = &TMP103[188];
TMP103[188].kind = 1;
TMP103[188].offset = offsetof(TY38511, Containerflag0);
TMP103[188].typ = NTI114;
chckNil(TMP103[188].typ);
TMP103[188].name = "Container_flag0";
TMP103[186].len = 2; TMP103[186].kind = 2; TMP103[186].sons = &TMP124038[0];
NTI38511->node = &TMP103[186];
NTI38519->size = sizeof(TY38519);
NTI38519->kind = 17;
NTI38519->base = NTI38511;
NTI38519->flags = 3;
TMP103[189].kind = 1;
TMP103[189].offset = offsetof(TY38519, Child);
TMP103[189].typ = NTI38213;
chckNil(TMP103[189].typ);
TMP103[189].name = "child";
NTI38519->node = &TMP103[189];
NTI38531->size = sizeof(TY38531);
NTI38531->kind = 17;
NTI38531->base = NTI38519;
NTI38531->flags = 3;
TMP124039[0] = &TMP103[191];
TMP103[191].kind = 1;
TMP103[191].offset = offsetof(TY38531, Title);
TMP103[191].typ = NTI132;
chckNil(TMP103[191].typ);
TMP103[191].name = "title";
TMP124039[1] = &TMP103[192];
TMP103[192].kind = 1;
TMP103[192].offset = offsetof(TY38531, Wmclassname);
TMP103[192].typ = NTI132;
chckNil(TMP103[192].typ);
TMP103[192].name = "wmclass_name";
TMP124039[2] = &TMP103[193];
TMP103[193].kind = 1;
TMP103[193].offset = offsetof(TY38531, Wmclassclass);
TMP103[193].typ = NTI132;
chckNil(TMP103[193].typ);
TMP103[193].name = "wmclass_class";
TMP124039[3] = &TMP103[194];
TMP103[194].kind = 1;
TMP103[194].offset = offsetof(TY38531, Wmrole);
TMP103[194].typ = NTI132;
chckNil(TMP103[194].typ);
TMP103[194].name = "wm_role";
TMP124039[4] = &TMP103[195];
TMP103[195].kind = 1;
TMP103[195].offset = offsetof(TY38531, Focuswidget);
TMP103[195].typ = NTI38213;
chckNil(TMP103[195].typ);
TMP103[195].name = "focus_widget";
TMP124039[5] = &TMP103[196];
TMP103[196].kind = 1;
TMP103[196].offset = offsetof(TY38531, Defaultwidget);
TMP103[196].typ = NTI38213;
chckNil(TMP103[196].typ);
TMP103[196].name = "default_widget";
TMP124039[6] = &TMP103[197];
TMP103[197].kind = 1;
TMP103[197].offset = offsetof(TY38531, Transientparent);
TMP103[197].typ = NTI38529;
chckNil(TMP103[197].typ);
TMP103[197].name = "transient_parent";
TMP124039[7] = &TMP103[198];
TMP103[198].kind = 1;
TMP103[198].offset = offsetof(TY38531, Geometryinfo);
TMP103[198].typ = NTI134;
chckNil(TMP103[198].typ);
TMP103[198].name = "geometry_info";
TMP124039[8] = &TMP103[199];
TMP103[199].kind = 1;
TMP103[199].offset = offsetof(TY38531, Frame);
TMP103[199].typ = NTI31222;
chckNil(TMP103[199].typ);
TMP103[199].name = "frame";
TMP124039[9] = &TMP103[200];
NTI38537->size = sizeof(TY38537);
NTI38537->kind = 17;
NTI38537->base = NTI18896;
NTI38537->flags = 3;
TMP103[201].kind = 1;
TMP103[201].offset = offsetof(TY38537, Grabs);
TMP103[201].typ = NTI17376;
chckNil(TMP103[201].typ);
TMP103[201].name = "grabs";
NTI38537->node = &TMP103[201];
NTI38527->size = sizeof(TY38537*);
NTI38527->kind = 21;
NTI38527->base = NTI38537;
NTI38527->flags = 3;
TMP103[200].kind = 1;
TMP103[200].offset = offsetof(TY38531, Group);
TMP103[200].typ = NTI38527;
chckNil(TMP103[200].typ);
TMP103[200].name = "group";
TMP124039[10] = &TMP103[202];
TMP103[202].kind = 1;
TMP103[202].offset = offsetof(TY38531, Configurerequestcount);
TMP103[202].typ = NTI112;
chckNil(TMP103[202].typ);
TMP103[202].name = "configure_request_count";
TMP124039[11] = &TMP103[203];
TMP103[203].kind = 1;
TMP103[203].offset = offsetof(TY38531, Windowflag0);
TMP103[203].typ = NTI114;
chckNil(TMP103[203].typ);
TMP103[203].name = "window_flag0";
TMP124039[12] = &TMP103[204];
TMP103[204].kind = 1;
TMP103[204].offset = offsetof(TY38531, Frameleft);
TMP103[204].typ = NTI114;
chckNil(TMP103[204].typ);
TMP103[204].name = "frame_left";
TMP124039[13] = &TMP103[205];
TMP103[205].kind = 1;
TMP103[205].offset = offsetof(TY38531, Frametop);
TMP103[205].typ = NTI114;
chckNil(TMP103[205].typ);
TMP103[205].name = "frame_top";
TMP124039[14] = &TMP103[206];
TMP103[206].kind = 1;
TMP103[206].offset = offsetof(TY38531, Frameright);
TMP103[206].typ = NTI114;
chckNil(TMP103[206].typ);
TMP103[206].name = "frame_right";
TMP124039[15] = &TMP103[207];
TMP103[207].kind = 1;
TMP103[207].offset = offsetof(TY38531, Framebottom);
TMP103[207].typ = NTI114;
chckNil(TMP103[207].typ);
TMP103[207].name = "frame_bottom";
TMP124039[16] = &TMP103[208];
TMP103[208].kind = 1;
TMP103[208].offset = offsetof(TY38531, Keyschangedhandler);
TMP103[208].typ = NTI114;
chckNil(TMP103[208].typ);
TMP103[208].name = "keys_changed_handler";
TMP124039[17] = &TMP103[209];
TMP103[209].kind = 1;
TMP103[209].offset = offsetof(TY38531, Mnemonicmodifier);
TMP103[209].typ = NTI114;
chckNil(TMP103[209].typ);
TMP103[209].name = "mnemonic_modifier";
TMP124039[18] = &TMP103[210];
TMP103[210].kind = 1;
TMP103[210].offset = offsetof(TY38531, Screen);
TMP103[210].typ = NTI31296;
chckNil(TMP103[210].typ);
TMP103[210].name = "screen";
TMP103[190].len = 19; TMP103[190].kind = 2; TMP103[190].sons = &TMP124039[0];
NTI38531->node = &TMP103[190];
NTI38529->size = sizeof(TY38531*);
NTI38529->kind = 21;
NTI38529->base = NTI38531;
NTI38529->flags = 3;
TMP103[55].kind = 1;
TMP103[55].offset = offsetof(TY124002, W);
TMP103[55].typ = NTI38529;
chckNil(TMP103[55].typ);
TMP103[55].name = "w";
TMP124016[1] = &TMP103[211];
NTI66010->size = sizeof(TY66010);
NTI66010->kind = 40;
NTI66010->base = 0;
NTI66010->flags = 3;
TMP103[212].len = 0; TMP103[212].kind = 2;
NTI66010->node = &TMP103[212];
NTI66012->size = sizeof(TY66010*);
NTI66012->kind = 21;
NTI66012->base = NTI66010;
NTI66012->flags = 3;
TMP103[211].kind = 1;
TMP103[211].offset = offsetof(TY124002, Nimlang);
TMP103[211].typ = NTI66012;
chckNil(TMP103[211].typ);
TMP103[211].name = "nimLang";
TMP124016[2] = &TMP103[213];
NTI39403->size = sizeof(TY39403);
NTI39403->kind = 17;
NTI39403->base = NTI38511;
NTI39403->flags = 3;
TMP124040[0] = &TMP103[215];
TMP103[215].kind = 1;
TMP103[215].offset = offsetof(TY39403, Curpage);
TMP103[215].typ = NTI134;
chckNil(TMP103[215].typ);
TMP103[215].name = "cur_page";
TMP124040[1] = &TMP103[216];
NTI17384->size = sizeof(TY17384);
NTI17384->kind = 40;
NTI17384->base = 0;
NTI17384->flags = 3;
TMP124041[0] = &TMP103[218];
TMP103[218].kind = 1;
TMP103[218].offset = offsetof(TY17384, Data);
TMP103[218].typ = NTI134;
chckNil(TMP103[218].typ);
TMP103[218].name = "data";
TMP124041[1] = &TMP103[219];
TMP103[219].kind = 1;
TMP103[219].offset = offsetof(TY17384, Next);
TMP103[219].typ = NTI17382;
chckNil(TMP103[219].typ);
TMP103[219].name = "next";
TMP124041[2] = &TMP103[220];
TMP103[220].kind = 1;
TMP103[220].offset = offsetof(TY17384, Prev);
TMP103[220].typ = NTI17382;
chckNil(TMP103[220].typ);
TMP103[220].name = "prev";
TMP103[217].len = 3; TMP103[217].kind = 2; TMP103[217].sons = &TMP124041[0];
NTI17384->node = &TMP103[217];
NTI17382->size = sizeof(TY17384*);
NTI17382->kind = 21;
NTI17382->base = NTI17384;
NTI17382->flags = 3;
TMP103[216].kind = 1;
TMP103[216].offset = offsetof(TY39403, Children);
TMP103[216].typ = NTI17382;
chckNil(TMP103[216].typ);
TMP103[216].name = "children";
TMP124040[2] = &TMP103[221];
TMP103[221].kind = 1;
TMP103[221].offset = offsetof(TY39403, Firsttab);
TMP103[221].typ = NTI17382;
chckNil(TMP103[221].typ);
TMP103[221].name = "first_tab";
TMP124040[3] = &TMP103[222];
TMP103[222].kind = 1;
TMP103[222].offset = offsetof(TY39403, Focustab);
TMP103[222].typ = NTI17382;
chckNil(TMP103[222].typ);
TMP103[222].name = "focus_tab";
TMP124040[4] = &TMP103[223];
TMP103[223].kind = 1;
TMP103[223].offset = offsetof(TY39403, Menu);
TMP103[223].typ = NTI38213;
chckNil(TMP103[223].typ);
TMP103[223].name = "menu";
TMP124040[5] = &TMP103[224];
TMP103[224].kind = 1;
TMP103[224].offset = offsetof(TY39403, Eventwindow);
TMP103[224].typ = NTI31222;
chckNil(TMP103[224].typ);
TMP103[224].name = "event_window";
TMP124040[6] = &TMP103[225];
TMP103[225].kind = 1;
TMP103[225].offset = offsetof(TY39403, Timer);
TMP103[225].typ = NTI114;
chckNil(TMP103[225].typ);
TMP103[225].name = "timer";
TMP124040[7] = &TMP103[226];
TMP103[226].kind = 1;
TMP103[226].offset = offsetof(TY39403, Tabhborder);
TMP103[226].typ = NTI112;
chckNil(TMP103[226].typ);
TMP103[226].name = "tab_hborder";
TMP124040[8] = &TMP103[227];
TMP103[227].kind = 1;
TMP103[227].offset = offsetof(TY39403, Tabvborder);
TMP103[227].typ = NTI112;
chckNil(TMP103[227].typ);
TMP103[227].name = "tab_vborder";
TMP124040[9] = &TMP103[228];
TMP103[228].kind = 1;
TMP103[228].offset = offsetof(TY39403, Notebookflag0);
TMP103[228].typ = NTI112;
chckNil(TMP103[228].typ);
TMP103[228].name = "Notebook_flag0";
TMP103[214].len = 10; TMP103[214].kind = 2; TMP103[214].sons = &TMP124040[0];
NTI39403->node = &TMP103[214];
NTI39401->size = sizeof(TY39403*);
NTI39401->kind = 21;
NTI39401->base = NTI39403;
NTI39401->flags = 3;
TMP103[213].kind = 1;
TMP103[213].offset = offsetof(TY124002, Sourceviewtabs);
TMP103[213].typ = NTI39401;
chckNil(TMP103[213].typ);
TMP103[213].name = "SourceViewTabs";
TMP124016[3] = &TMP103[229];
NTI38629->size = sizeof(TY38629);
NTI38629->kind = 17;
NTI38629->base = NTI38511;
NTI38629->flags = 3;
TMP124042[0] = &TMP103[231];
TMP103[231].kind = 1;
TMP103[231].offset = offsetof(TY38629, Children);
TMP103[231].typ = NTI17382;
chckNil(TMP103[231].typ);
TMP103[231].name = "children";
TMP124042[1] = &TMP103[232];
TMP103[232].kind = 1;
TMP103[232].offset = offsetof(TY38629, Spacing);
TMP103[232].typ = NTI112;
chckNil(TMP103[232].typ);
TMP103[232].name = "spacing";
TMP124042[2] = &TMP103[233];
TMP103[233].kind = 1;
TMP103[233].offset = offsetof(TY38629, Boxflag0);
TMP103[233].typ = NTI112;
chckNil(TMP103[233].typ);
TMP103[233].name = "box_flag0";
TMP103[230].len = 3; TMP103[230].kind = 2; TMP103[230].sons = &TMP124042[0];
NTI38629->node = &TMP103[230];
NTI38871->size = sizeof(TY38871);
NTI38871->kind = 17;
NTI38871->base = NTI38629;
NTI38871->flags = 3;
TMP103[234].len = 0; TMP103[234].kind = 2;
NTI38871->node = &TMP103[234];
NTI39571->size = sizeof(TY39571);
NTI39571->kind = 17;
NTI39571->base = NTI38871;
NTI39571->flags = 3;
TMP124043[0] = &TMP103[236];
TMP103[236].kind = 1;
TMP103[236].offset = offsetof(TY39571, Frame);
TMP103[236].typ = NTI38213;
chckNil(TMP103[236].typ);
TMP103[236].name = "frame";
TMP124043[1] = &TMP103[237];
TMP103[237].kind = 1;
TMP103[237].offset = offsetof(TY39571, Label);
TMP103[237].typ = NTI38213;
chckNil(TMP103[237].typ);
TMP103[237].name = "label";
TMP124043[2] = &TMP103[238];
TMP103[238].kind = 1;
TMP103[238].offset = offsetof(TY39571, Messages);
TMP103[238].typ = NTI17376;
chckNil(TMP103[238].typ);
TMP103[238].name = "messages";
TMP124043[3] = &TMP103[239];
TMP103[239].kind = 1;
TMP103[239].offset = offsetof(TY39571, Keys);
TMP103[239].typ = NTI17376;
chckNil(TMP103[239].typ);
TMP103[239].name = "keys";
TMP124043[4] = &TMP103[240];
TMP103[240].kind = 1;
TMP103[240].offset = offsetof(TY39571, Seqcontextid);
TMP103[240].typ = NTI114;
chckNil(TMP103[240].typ);
TMP103[240].name = "seq_context_id";
TMP124043[5] = &TMP103[241];
TMP103[241].kind = 1;
TMP103[241].offset = offsetof(TY39571, Seqmessageid);
TMP103[241].typ = NTI114;
chckNil(TMP103[241].typ);
TMP103[241].name = "seq_message_id";
TMP124043[6] = &TMP103[242];
TMP103[242].kind = 1;
TMP103[242].offset = offsetof(TY39571, Gripwindow);
TMP103[242].typ = NTI31222;
chckNil(TMP103[242].typ);
TMP103[242].name = "grip_window";
TMP124043[7] = &TMP103[243];
TMP103[243].kind = 1;
TMP103[243].offset = offsetof(TY39571, Statusbarflag0);
TMP103[243].typ = NTI112;
chckNil(TMP103[243].typ);
TMP103[243].name = "Statusbar_flag0";
TMP103[235].len = 8; TMP103[235].kind = 2; TMP103[235].sons = &TMP124043[0];
NTI39571->node = &TMP103[235];
NTI39569->size = sizeof(TY39571*);
NTI39569->kind = 21;
NTI39569->base = NTI39571;
NTI39569->flags = 3;
TMP103[229].kind = 1;
TMP103[229].offset = offsetof(TY124002, Bottombar);
TMP103[229].typ = NTI39569;
chckNil(TMP103[229].typ);
TMP103[229].name = "bottomBar";
TMP124016[4] = &TMP103[244];
NTI124004->size = sizeof(TY124004);
NTI124004->kind = 17;
NTI124004->base = 0;
NTI124004->flags = 2;
TMP124044[0] = &TMP103[246];
NTI39719->size = sizeof(TY39719);
NTI39719->kind = 17;
NTI39719->base = NTI18896;
NTI39719->flags = 3;
TMP124045[0] = &TMP103[248];
NTI39645->size = sizeof(TY39645);
NTI39645->kind = 17;
NTI39645->base = NTI18896;
NTI39645->flags = 3;
TMP124046[0] = &TMP103[250];
TMP103[250].kind = 1;
TMP103[250].offset = offsetof(TY39645, Hash);
TMP103[250].typ = NTI134;
chckNil(TMP103[250].typ);
TMP103[250].name = "hash";
TMP124046[1] = &TMP103[251];
TMP103[251].kind = 1;
TMP103[251].offset = offsetof(TY39645, Anonymous);
TMP103[251].typ = NTI17376;
chckNil(TMP103[251].typ);
TMP103[251].name = "anonymous";
TMP124046[2] = &TMP103[252];
TMP103[252].kind = 1;
TMP103[252].offset = offsetof(TY39645, Anoncount);
TMP103[252].typ = NTI114;
chckNil(TMP103[252].typ);
TMP103[252].name = "anon_count";
TMP124046[3] = &TMP103[253];
TMP103[253].kind = 1;
TMP103[253].offset = offsetof(TY39645, Buffers);
TMP103[253].typ = NTI17376;
chckNil(TMP103[253].typ);
TMP103[253].name = "buffers";
TMP103[249].len = 4; TMP103[249].kind = 2; TMP103[249].sons = &TMP124046[0];
NTI39645->node = &TMP103[249];
NTI38379->size = sizeof(TY39645*);
NTI38379->kind = 21;
NTI38379->base = NTI39645;
NTI38379->flags = 3;
TMP103[248].kind = 1;
TMP103[248].offset = offsetof(TY39719, Tagtable);
TMP103[248].typ = NTI38379;
chckNil(TMP103[248].typ);
TMP103[248].name = "tag_table";
TMP124045[1] = &TMP103[254];
TMP103[254].kind = 1;
TMP103[254].offset = offsetof(TY39719, Btree);
TMP103[254].typ = NTI134;
chckNil(TMP103[254].typ);
TMP103[254].name = "btree";
TMP124045[2] = &TMP103[255];
TMP103[255].kind = 1;
TMP103[255].offset = offsetof(TY39719, Clipboardcontentsbuffers);
TMP103[255].typ = NTI17376;
chckNil(TMP103[255].typ);
TMP103[255].name = "clipboard_contents_buffers";
TMP124045[3] = &TMP103[256];
TMP103[256].kind = 1;
TMP103[256].offset = offsetof(TY39719, Selectionclipboards);
TMP103[256].typ = NTI17376;
chckNil(TMP103[256].typ);
TMP103[256].name = "selection_clipboards";
TMP124045[4] = &TMP103[257];
TMP103[257].kind = 1;
TMP103[257].offset = offsetof(TY39719, Logattrcache);
TMP103[257].typ = NTI134;
chckNil(TMP103[257].typ);
TMP103[257].name = "log_attr_cache";
TMP124045[5] = &TMP103[258];
TMP103[258].kind = 1;
TMP103[258].offset = offsetof(TY39719, Useractioncount);
TMP103[258].typ = NTI114;
chckNil(TMP103[258].typ);
TMP103[258].name = "user_action_count";
TMP124045[6] = &TMP103[259];
TMP103[259].kind = 1;
TMP103[259].offset = offsetof(TY39719, Textbufferflag0);
TMP103[259].typ = NTI112;
chckNil(TMP103[259].typ);
TMP103[259].name = "TextBuffer_flag0";
TMP103[247].len = 7; TMP103[247].kind = 2; TMP103[247].sons = &TMP124045[0];
NTI39719->node = &TMP103[247];
NTI66014->size = sizeof(TY66014);
NTI66014->kind = 17;
NTI66014->base = NTI39719;
NTI66014->flags = 3;
TMP103[260].len = 0; TMP103[260].kind = 2;
NTI66014->node = &TMP103[260];
NTI66016->size = sizeof(TY66014*);
NTI66016->kind = 21;
NTI66016->base = NTI66014;
NTI66016->flags = 3;
TMP103[246].kind = 1;
TMP103[246].offset = offsetof(TY124004, Buffer);
TMP103[246].typ = NTI66016;
chckNil(TMP103[246].typ);
TMP103[246].name = "buffer";
TMP124044[1] = &TMP103[261];
TMP103[261].kind = 1;
TMP103[261].offset = offsetof(TY124004, Sourceview);
TMP103[261].typ = NTI38213;
chckNil(TMP103[261].typ);
TMP103[261].name = "sourceView";
TMP124044[2] = &TMP103[262];
NTI124->size = sizeof(NIM_BOOL);
NTI124->kind = 1;
NTI124->base = 0;
NTI124->flags = 3;
TMP103[262].kind = 1;
TMP103[262].offset = offsetof(TY124004, Saved);
TMP103[262].typ = NTI124;
chckNil(TMP103[262].typ);
TMP103[262].name = "saved";
TMP124044[3] = &TMP103[263];
TMP103[263].kind = 1;
TMP103[263].offset = offsetof(TY124004, Filename);
TMP103[263].typ = NTI130;
chckNil(TMP103[263].typ);
TMP103[263].name = "filename";
TMP103[245].len = 4; TMP103[245].kind = 2; TMP103[245].sons = &TMP124044[0];
NTI124004->node = &TMP103[245];
NTI124009->size = sizeof(TY124009*);
NTI124009->kind = 24;
NTI124009->base = NTI124004;
NTI124009->flags = 2;
TMP103[244].kind = 1;
TMP103[244].offset = offsetof(TY124002, Tabs);
TMP103[244].typ = NTI124009;
chckNil(TMP103[244].typ);
TMP103[244].name = "Tabs";
TMP103[54].len = 5; TMP103[54].kind = 2; TMP103[54].sons = &TMP124016[0];
NTI124002->node = &TMP103[54];
F.len = 0;
framePtr = framePtr->prev;
}

